### PR TITLE
use python-bitcoinlib 0.8.0 for segwit support

### PR DESCRIPTION
**Pull request by rubensayshi**

### CODE REVIEW

**Comment by deweller** [comment]
ack 5d1fd2c

**Comment by cryptcoin-junkey** [comment]
Have you tested it? AFAIK, python-bitcoinlib 0.8.0 doesn't have SegWit support. See the fork tree on python-bitcoinlib.

screenshot 2017-09-21 at 16

At least 0.8.0 doesn't work on my machine. So I sent PR #991.

**Comment by deweller** [comment]
@cryptcoin-junkey - You said 0.8.0 doesn't work on your machine.  Can you elaborate?  What happened?

**Comment by deweller** [comment]
You are correct that this doesn't actually fix the segwit serialization problem.

Please see https://github.com/CounterpartyXCP/counterparty-lib/pull/1001

**Pull request merged**
