### PR TITLE
Remove rpcthreads=100

### PR DESCRIPTION
**Pull request by unsystemizer**
This was never really proven to help, and by now it's almost 100% unnecessary and may even be harmful.

I added some other clarifications to the file.

### CODE REVIEW

**Comment by deweller** [comment]
ack f983769

**Comment by rubensayshi** [comment]
@deweller @unsystemizer has anyone been running without this sucesfully?

**Comment by deweller** [comment]
Looks like federated node uses `rpcthreads=50`.  Perhaps we should just change the readme to match that.

**Comment by deweller** [comment]
I've been running with the rcpthreads setting removed for a couple days now with no issues.

**Comment by rubensayshi** [comment]
needs rebase but ACK for this commit: https://github.com/CounterpartyXCP/counterparty-lib/pull/998/commits/f983769f1a7affa7b3895c068cb3160e097bf6ae

**Pull request closed without merging**
