### PR TITLE
Dispenser close delay

### PR DESCRIPTION
**Pull request by pataegrillo**

### CODE REVIEW

**Comment by jdogresorg** [comment]
## Dispenser Testing (source)
- Create dispenser on mznL38eTJrSbsik7LwtqzgzGgtjKRvrCQf - f7706c5bb675564e692f37e9d9503e4b3b102afeb6d84b922fd1c8fb8046c95f
  - Verify status is open (0) - OK
  - Verify funds debited from source - OK
- Send BTC to dispenser from mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt - 0088594be877b5fa0a7265b791d9869c115ab5f7d275b91daf72fa234f7a579b
  - Verify dispense is triggered - OK
  - Verify dispense is credited to buyer - OK
  - Verify dispenser is debited - OK
- Close dispenser from mznL38eTJrSbsik7LwtqzgzGgtjKRvrCQf - eee3034eb84f02926d617d04a3a3e2147ebd544ffe48b8185a64ba3c4ef843cb
  - Verify status is CLOSING (11) - OK
- Send BTC to dispenser from mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt - c4d5b3f1b5208d3e466ed6e2cdb2d92a9b840be20d29f21cef8b5acf067d7f70
  - Verify dispense is triggered - OK
  - Verify dispense is credited to buyer - OK
  - Verify dispenser is debited - OK
  - Verify status is CLOSING (11) - OK
- Wait 5 blocks for dispenser to close - DONE
  - Verify status is CLOSED (10) - OK

```
[2023-11-06 22:48:04][INFO] Dispenser: mznL38eTJrSbsik7LwtqzgzGgtjKRvrCQf opened a dispenser for asset BACONTITS with 10.00000000 balance, giving 1.00000000 BACONTITS for each 0.00001000 BTC
[2023-11-06 22:48:04][INFO] Block: 2537249 (0.15s, hashes: L:d6445 / TX:054b6 / M:962b8)
[2023-11-06 23:08:37][INFO] Dispense: 1.0 BACONTITS from mznL38eTJrSbsik7LwtqzgzGgtjKRvrCQf to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt (0088594be877b5fa0a7265b791d9869c115ab5f7d275b91daf72fa234f7a579b)
[2023-11-06 23:08:37][INFO] Block: 2537250 (0.17s, hashes: L:d2f79 / TX:f6f27 / M:1a82b)
[2023-11-06 23:09:35][INFO] Block: 2537251 (0.14s, hashes: L:bc947 / TX:d4a11 / M:dc087)
[2023-11-06 23:12:20][INFO] Dispenser: mznL38eTJrSbsik7LwtqzgzGgtjKRvrCQf closed dispenser for BACONTITS (operator marked the dispenser to close it)
[2023-11-06 23:12:20][INFO] Block: 2537252 (0.18s, hashes: L:1cb83 / TX:61ff6 / M:92203)
[2023-11-07 03:23:54][INFO] Dispense: 1.0 BACONTITS from mznL38eTJrSbsik7LwtqzgzGgtjKRvrCQf to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt (c4d5b3f1b5208d3e466ed6e2cdb2d92a9b840be20d29f21cef8b5acf067d7f70)
[2023-11-07 03:23:54][INFO] Block: 2537253 (0.03s, hashes: L:1dfb4 / TX:fb906 / M:0fe7f)
[2023-11-07 03:23:54][INFO] Block: 2537254 (0.03s, hashes: L:7a2e5 / TX:8099f / M:3d1e4)
[2023-11-07 03:23:54][INFO] Block: 2537255 (0.04s, hashes: L:8c73d / TX:a236d / M:562e8)
[2023-11-07 03:23:55][INFO] Block: 2537256 (0.05s, hashes: L:52f8d / TX:6e648 / M:79994)
[2023-11-07 03:23:55][INFO] Dispenser: mznL38eTJrSbsik7LwtqzgzGgtjKRvrCQf closed dispenser for BACONTITS (operator closed)
[2023-11-07 03:23:55][INFO] Block: 2537257 (0.02s, hashes: L:71c5d / TX:4ac72 / M:b8dd9)
```

**Comment by jdogresorg** [comment]
## Dispenser Testing (EMPTY)
- Create dispenser on EMPTY address tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 - 7510896a0a232eb814278f563d9c6e83ec6e97561bc4447257ff28603a1cf334
  - Verify status is open (0) - OK
  - Verify funds debited from origin - OK
- Send BTC to dispenser from mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt - 8f0e74bb971c0d9e24ab842ba358087383539c6fc15d44edfb3d9a73988a339d
  - Verify dispense is triggered - OK
  - Verify dispense is credited to buyer - OK
  - Verify dispenser is debited - OK
- Close dispenser from `origin` - e0226ba71237e028e46ad4d7c5fbdd595b4c83d1eb53543dd53cf9d342671b7c
  - Verify status is CLOSING (11) - OK
- Send BTC to dispenser from mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt to buy out dispenser - 9636a28de1f86560f5fa40cddd52695dbc27f7be7c1f1d6d04e358801b8f35ea
  - Verify dispense is triggered - OK
  - Verify status is CLOSED (10) - OK
- Wait 5 blocks
  - Verify status is CLOSED (10) - OK

```
2023-11-07 18:03:37][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 opened a dispenser for asset BACONTITS with 10.00000000 balance, giving 1.00000000 BACONTITS for each 0.00001000 BTC
2023-11-07 18:03:37][INFO] Block: 2537371 (0.19s, hashes: L:604af / TX:99ffa / M:ed7f0)
2023-11-07 18:56:29][INFO] Dispense: 1.0 BACONTITS from tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt (8f0e74bb971c0d9e24ab842ba358087383539c6fc15d44edfb3d9a73988a339d)
2023-11-07 18:56:29][INFO] Block: 2537376 (0.16s, hashes: L:17bea / TX:0b3c5 / M:50703)
2023-11-07 23:34:44][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 closed dispenser for BACONTITS (marked to close by origin)
2023-11-07 23:34:45][INFO] Block: 2537410 (0.16s, hashes: L:a56e3 / TX:ee019 / M:46284)
2023-11-07 23:35:04][INFO] Block: 2537411 (0.14s, hashes: L:cf14c / TX:99d16 / M:7bf24)
2023-11-07 23:45:00][INFO] Block: 2537412 (0.17s, hashes: L:4f9d3 / TX:28fb4 / M:3f242)
2023-11-07 23:48:48][INFO] Block: 2537413 (0.15s, hashes: L:19772 / TX:14a10 / M:a6ccf)
2023-11-07 23:59:08][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 closed dispenser for BACONTITS (dispenser empty)
2023-11-07 23:59:08][INFO] Dispense: 9.0 BACONTITS from tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt (9636a28de1f86560f5fa40cddd52695dbc27f7be7c1f1d6d04e358801b8f35ea)
2023-11-07 23:59:08][INFO] Block: 2537414 (0.15s, hashes: L:5b868 / TX:5a514 / M:2dc09)
2023-11-08 00:07:11][INFO] Block: 2537415 (0.16s, hashes: L:7b22d / TX:fdc63 / M:01080)
```

**Comment by jdogresorg** [comment]
## Dispenser Testing (`origin` / reopen)
- Create dispenser on EMPTY address tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 - 3017c99e6902d1d377a5215bebcbede33932730ef0f988b6f57fc2d19dede0cc
  - Verify status is open (0) - OK
  - Verify funds debited from origin - OK
- Send BTC to dispenser from mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt - 990887ead754433581e9aa2a4ef8ef69accd821cc45986780ba68fc4d798e56a
  - Verify dispense is triggered - OK
  - Verify dispense is credited to buyer - OK
  - Verify dispenser is debited - OK
- Close dispenser from `origin` - c8e4668d9a9b9521f38fa99ff9653cae3c09cbc4eea8c964be3fa5df4a4bb3d1
  - Verify status is CLOSING (11) - OK
- Send BTC to dispenser from mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt - b0126b9321da548ecce5cdb35a7eb03f98fd85e0c38485ce947338351c08d97b
  - Verify dispense is triggered - OK
  - Verify status is CLOSING (11) - OK
- Wait 5 blocks for dispenser to close - DONE
  - Verify status is CLOSED (10) -  OK

```
[2023-11-08 00:27:12][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 opened a dispenser for asset BACONTITS with 10.00000000 balance, giving 1.00000000 BACONTITS for each 0.00001000 BTC
[2023-11-08 00:27:12][INFO] Block: 2537416 (0.16s, hashes: L:e6092 / TX:7191e / M:ce081)
[2023-11-08 00:31:44][INFO] Block: 2537418 (0.17s, hashes: L:70078 / TX:5bf78 / M:5f9b1)
[2023-11-08 00:34:16][INFO] Block: 2537419 (0.15s, hashes: L:11767 / TX:9f172 / M:85a53)
[2023-11-08 00:35:52][INFO] Dispense: 2.0 BACONTITS from tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt (990887ead754433581e9aa2a4ef8ef69accd821cc45986780ba68fc4d798e56a)
[2023-11-08 00:35:52][INFO] Block: 2537420 (0.15s, hashes: L:f4d32 / TX:b4387 / M:17856)
[2023-11-08 00:36:19][INFO] Block: 2537421 (0.16s, hashes: L:28ea1 / TX:1b588 / M:3ddf0)
[2023-11-08 00:56:18][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 closed dispenser for BACONTITS (marked to close by origin)
[2023-11-08 00:56:18][INFO] Block: 2537422 (0.20s, hashes: L:0b64c / TX:19a26 / M:b4c82)
[2023-11-08 01:05:45][INFO] Dispense: 3.0 BACONTITS from tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt (b0126b9321da548ecce5cdb35a7eb03f98fd85e0c38485ce947338351c08d97b)
[2023-11-08 01:05:45][INFO] Block: 2537423 (0.16s, hashes: L:50e68 / TX:19430 / M:7995c)
[2023-11-08 01:10:18][INFO] Block: 2537424 (0.15s, hashes: L:ac11b / TX:51dc8 / M:ca1b8)
[2023-11-08 01:11:24][INFO] Block: 2537425 (0.14s, hashes: L:50529 / TX:7c06a / M:12a1a)
[2023-11-08 01:17:34][INFO] Block: 2537426 (0.14s, hashes: L:fd66d / TX:724e8 / M:59ea0)
[2023-11-08 01:17:44][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 closed dispenser for BACONTITS (closed by origin)
[2023-11-08 01:17:44][INFO] Block: 2537427 (0.14s, hashes: L:44cce / TX:ec8bf / M:75036)
```

**Comment by jdogresorg** [comment]
## Dispenser Testing (oracle)
- Create dispenser on EMPTY address tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 using oracle mmUSDD66Q883cnYygZ5v26xaY35U7S9uwh - 0604af3f71bf2ec4d2c0609d1d2b7efcf0b32567617b6a46c75a8cd3c8614c67
  - Verify status is open (0) - OK
  - Verify funds debited from origin - OK
- Send BTC to dispenser from mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt - 4199b3e186d1f2e2bbfd5e5d8101d4ee32e414b5edce3dfcc4fda2f7566cd790
  - Verify dispense is triggered - OK
  - Verify dispense is credited to buyer - OK
  - Verify dispenser is debited - OK
- Close dispenser from `origin` - 0f6f20d211758970564efd0a94f00c6b7b9591264aee6dee912880c3e89ed737
  - Verify status is CLOSING (11) - OK
- Send BTC to dispenser from mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt - f54d6cdeb4694842303f289d98a1704cea64ec69ec8cd6d673321b3f75664015
  - Verify dispense is triggered - OK
  - Verify status is CLOSING (11) - OK
- Wait 5 blocks for dispenser to close - DONE
  - Verify status is CLOSED (10) - OK

```
[2023-11-08 01:36:13][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 opened a oracle dispenser using mmUSDD66Q883cnYygZ5v26xaY35U7S9uwh for asset BACONTITS with 10.00000000 balance, giving 1.00000000 BACONTITS for each 10.00 USD
[2023-11-08 01:36:13][INFO] Block: 2537429 (0.16s, hashes: L:20799 / TX:185ae / M:bd82b)
[2023-11-08 01:37:18][INFO] Block: 2537430 (0.14s, hashes: L:52761 / TX:fc652 / M:3a6d0)
[2023-11-08 01:37:45][INFO] Block: 2537431 (0.14s, hashes: L:a154b / TX:8e30f / M:7d8c6)
[2023-11-08 01:53:55][INFO] Dispense: 1.0 BACONTITS from tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt for 0.00028306 BTC (10.0 USD) (4199b3e186d1f2e2bbfd5e5d8101d4ee32e414b5edce3dfcc4fda2f7566cd790)
[2023-11-08 01:53:55][INFO] Block: 2537432 (0.20s, hashes: L:c146c / TX:cb306 / M:eaef9)
[2023-11-08 01:55:03][INFO] Block: 2537433 (0.16s, hashes: L:45d6c / TX:60351 / M:3c845)
[2023-11-08 01:56:10][INFO] Block: 2537434 (0.14s, hashes: L:0f12d / TX:5ca68 / M:dead3)
[2023-11-08 01:56:14][INFO] Block: 2537435 (0.14s, hashes: L:507e4 / TX:f82f8 / M:b40c6)
[2023-11-08 02:05:47][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 closed dispenser for BACONTITS (marked to close by origin)
[2023-11-08 02:05:47][INFO] Dispense: 2.0 BACONTITS from tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt for 0.00060000 BTC (21.2 USD) (f54d6cdeb4694842303f289d98a1704cea64ec69ec8cd6d673321b3f75664015)
[2023-11-08 02:05:47][INFO] Block: 2537436 (0.19s, hashes: L:b87ee / TX:bb956 / M:fa217)
[2023-11-08 02:12:39][INFO] Block: 2537437 (0.15s, hashes: L:4122d / TX:80d3a / M:5d4f2)
[2023-11-08 02:13:42][INFO] Block: 2537438 (0.14s, hashes: L:8ec19 / TX:d16bd / M:93d0d)
[2023-11-08 02:29:49][INFO] Block: 2537440 (0.15s, hashes: L:fb318 / TX:dd2fe / M:789bb)
[2023-11-08 02:20:41][INFO] Block: 2537439 (0.15s, hashes: L:4e7e9 / TX:5ad6f / M:0fbcd)
[2023-11-08 02:31:13][INFO] Dispenser: tb1qjpu5ur3jkdv44svfcyr8zjw4j293zywqzcgn23 closed dispenser for BACONTITS (closed by origin)
[2023-11-08 02:31:14][INFO] Block: 2537441 (0.14s, hashes: L:55c2f / TX:d747c / M:6f64c)
```

**Comment by jdogresorg** [comment]
Looks good in testing.

**Comment by Jpja** [comment]
This does not solve much and negatively affects [CIP32 Dispenser Reservation](https://github.com/CounterpartyXCP/cips/blob/master/cip-0032.md).

My concerns with delayed dispensers have not been answered. https://github.com/CounterpartyXCP/cips/discussions/120

NACK

**Pull request merged**
