### PR TITLE
Max Free Fraction of 1; Don't Match on Invalid Broadcast

### PR DESCRIPTION
**Pull request by adamkrellenstein**

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
@ouziel-slama, @rubensayshi, @robby-dermody

**Comment by ouziel-slama** [comment]
ACK!

**Comment by robby-dermody** [comment]
utACK

**Comment by adamkrellenstein** [comment]
@ouziel-slama good fixes

**Comment by rubensayshi** [comment]
ACK

**Pull request merged**
