### PR TITLE
- CIP03, token reset

### PR DESCRIPTION
**Pull request by pataegrillo**

### CODE REVIEW

**Comment by jdogresorg** [comment]
Please update protocol_changes.json with activation blocks for CIP03 

mainnet: 753000
testnet: 2288000

**Comment by jdogresorg** [comment]
https://github.com/CounterpartyXCP/counterparty-lib/pull/1193/files/042c8a20754207ac0894ba807f59804cbdd0610e#diff-55d711a254203487dc56fcf7bd8ccd382ab047979f92792fdba074f890316415R271-R273

This line concerns me as I believe we should be able to reset token supply even if there is no actual supply.

When a user does an issuance, they are forced to pick divisible or non-divisible property for their asset, even if they issue no supply.

We should allow asset owners who have 0 holders (never issued any supply) to reset their token divisibility status and issue supply. The only difference here would be that we would not need to destroy any existing supply since none exists, we would just issue new supply with the divisibility set to whatever the user desires.

**Comment by pataegrillo** [comment]
> https://github.com/CounterpartyXCP/counterparty-lib/pull/1193/files/042c8a20754207ac0894ba807f59804cbdd0610e#diff-55d711a254203487dc56fcf7bd8ccd382ab047979f92792fdba074f890316415R271-R273
> 
> This line concerns me as I believe we should be able to reset token supply even if there is no actual supply.
> 
> When a user does an issuance, they are forced to pick divisible or non-divisible property for their asset, even if they issue no supply.
> 
> We should allow asset owners who have 0 holders (never issued any supply) to reset their token divisibility status and issue supply. The only difference here would be that we would not need to destroy any existing supply since none exists, we would just issue new supply with the divisibility set to whatever the user desires.

Look at the second line, it checks if the asset has any supply. An asset with supply but no owner can be a problem. This case will most likely never happen because of the sanity checks, but this line prevents potential disaster. However, 0 supply assets will not have any problem being reset

**Comment by jdogresorg** [comment]
- Issue new asset / Lock (ISSUELOCK) - works but doesnt show issuance in console
https://testnet.xchain.io/tx/e54ba0e83df04e1100bab2c1241964a23a8f6f371e64f59674e9941438cc7185

- Issue new asset / Transfer (ISSUEXFER) - only the txfer works.. supply not issued
https://testnet.xchain.io/tx/161ee4b7e63112c06d1945b95645030930b316cc08782231caa00ca1375006e8
https://testnet.xchain.io/tx/9af779013f26d122c19191ce4531857632efda7eb94ef076734138f5d743fd43

**Comment by jdogresorg** [comment]
CIP03 Testing
---

Issue 1.00000000 RESETTEST tokens - OK
https://testnet.xchain.io/tx/2eb7dcb1c703f4f086c5e0ab9328def7809ababca8a78e4fdca0206bba09806f

Reset supply to 1 RESETTEST tokens - OK
https://testnet.xchain.io/tx/0cd2a39bd195ebd3ced92fa31057094c46404f62d5ea6a3604e5231f2de75a89

Transfer ownership to new address (segwit) - OK
https://testnet.xchain.io/tx/764dc3d11e271356357ee073780c1ae0dbe26e11895ab331f3225b7b32f59e19

Transfer ownership back to original address (normal) - OK
https://testnet.xchain.io/tx/778c2ecdb6bb2f1967623f1cc28c49d01005cc182b8df8309ece5952dc6e2811

Issue 1 RESETTEST.SUBASSETA tokens - OK
https://testnet.xchain.io/tx/a4431666f4854fc990326db406e82dff1f88c8989ef5d2f76f5eb3c9c6b112ff

Reset supply to 100.00000000 RESETTEST.SUBASSETA tokens - OK
https://testnet.xchain.io/tx/ada9da9ec01d7581876655225d8b35507b15015cd684c4a467979169e0726fc6

Lock with "lock" param - OK
https://testnet.xchain.io/tx/754d8193e88d831c5059c4ffdd7db32fa69bfe1751a1ecac5d449f851e83870f

Lock with "LOCK" asset description - OK
https://testnet.xchain.io/tx/0cb516f41f9f7c966fd775e68d65bbd23caf5e367054d357986c066031bea21f

```
counterparty-testnet_1   | [2022-08-22 16:50:56][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 1.0 of divisible asset RESETTEST (2eb7dcb1c703f4f086c5e0ab9328def7809ababca8a78e4fdca0206bba09806f) [valid]
counterparty-testnet_1   | [2022-08-22 16:59:22][INFO] Destruction: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt destroyed 100000000 RESETTEST with tag ‘reset’(0cd2a39bd195ebd3ced92fa31057094c46404f62d5ea6a3604e5231f2de75a89) [valid]
counterparty-testnet_1   | [2022-08-22 16:59:22][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 1 of indivisible asset RESETTEST (0cd2a39bd195ebd3ced92fa31057094c46404f62d5ea6a3604e5231f2de75a89) [valid]
counterparty-testnet_1   | [2022-08-22 17:06:54][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt transfered asset RESETTEST to tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 (764dc3d11e271356357ee073780c1ae0dbe26e11895ab331f3225b7b32f59e19) [valid]
counterparty-testnet_1   | [2022-08-22 17:17:31][INFO] Issuance: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 transfered asset RESETTEST to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt (778c2ecdb6bb2f1967623f1cc28c49d01005cc182b8df8309ece5952dc6e2811) [valid]
counterparty-testnet_1   | [2022-08-22 20:34:20][INFO] Subasset Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 1 of indivisible subasset RESETTEST.SUBASSETA as numeric asset A16983615884910856590 (a4431666f4854fc990326db406e82dff1f88c8989ef5d2f76f5eb3c9c6b112ff) [valid]
counterparty-testnet_1   | [2022-08-22 20:39:51][INFO] Destruction: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt destroyed 1 A16983615884910856590 with tag ‘reset’(ada9da9ec01d7581876655225d8b35507b15015cd684c4a467979169e0726fc6) [valid]
counterparty-testnet_1   | [2022-08-22 20:39:51][INFO] Subasset Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 100.0 of divisible subasset RESETTEST.SUBASSETA as numeric asset A16983615884910856590 (ada9da9ec01d7581876655225d8b35507b15015cd684c4a467979169e0726fc6) [valid]
counterparty-testnet_1   | [2022-08-22 20:54:29][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt locked asset RESETTEST (754d8193e88d831c5059c4ffdd7db32fa69bfe1751a1ecac5d449f851e83870f) [valid]
counterparty-testnet_1   | [2022-08-22 21:20:11][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt locked asset A16983615884910856590 (0cb516f41f9f7c966fd775e68d65bbd23caf5e367054d357986c066031bea21f) [valid]
```

**Comment by jdogresorg** [comment]
- Issue / Lock - OK - but supply being issued is not logged to console
https://testnet.xchain.io/tx/711c80e894a1d08f816cfefe378daf0bc95d1ddf7816a6d2375b737eaf43c80b

- Issue / Transfer - OK - but supply being issued is not logged to console
https://testnet.xchain.io/tx/0639afad6ecc14a234c7b78bd205b44ca1bd5d93799aa966b8fb0975e8be2ad1

- Issue / Lock / Transfer - OK - but supply being issued is not logged to console
https://testnet.xchain.io/tx/3aad9035f33a63928693170847e52d761e8c3968409a469459fee6c6ee7f6906

```
counterparty-testnet_1   | [2022-08-22 23:21:37][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt transfered asset ISSUEXFERB to tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 (0639afad6ecc14a234c7b78bd205b44ca1bd5d93799aa966b8fb0975e8be2ad1) [valid]
counterparty-testnet_1   | [2022-08-22 23:21:37][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt locked asset ISSUELOCKB (711c80e894a1d08f816cfefe378daf0bc95d1ddf7816a6d2375b737eaf43c80b) [valid]
counterparty-testnet_1   | [2022-08-22 23:21:37][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt transfered asset LOCKXFERTEST to tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 (3aad9035f33a63928693170847e52d761e8c3968409a469459fee6c6ee7f6906) [valid]
```

**Comment by jdogresorg** [comment]
Getting error when trying to do issue/lock in a single tx after the latest log.py update

```counterparty-testnet_1   | [2022-08-23 15:53:57][WARNING] ParseTransactionError for tx 61e2bd6c752eac1faf14776b87fed3d8893abfa137fb1fc2eac273060193417d: 'apsw.Connection' object has no attribute 'execute'
counterparty-testnet_1   | [2022-08-23 15:53:57][ERROR] Unhandled Exception
counterparty-testnet_1   | Traceback (most recent call last):
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 108, in parse_tx
counterparty-testnet_1   |     issuance.parse(db, tx, message, message_type_id)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/messages/issuance.py", line 606, in parse
counterparty-testnet_1   |     issuance_parse_cursor.execute(sql, bindings)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/database.py", line 57, in exectracer
counterparty-testnet_1   |     log.message(db, bindings['block_index'], command, category, bindings)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/log.py", line 187, in message
counterparty-testnet_1   |     log(db, command, category, bindings)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/log.py", line 265, in log
counterparty-testnet_1   |     if get_asset_issuances_quantity(db, bindings["asset"]) == 1: #This is the first issuance, so we have to log the creation of the token
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/log.py", line 426, in get_asset_issuances_quantity
counterparty-testnet_1   |     cursor.execute('''SELECT COUNT(*) AS issuances_count FROM issuances \
counterparty-testnet_1   | AttributeError: 'apsw.Connection' object has no attribute 'execute'
counterparty-testnet_1   | 
counterparty-testnet_1   | During handling of the above exception, another exception occurred:
counterparty-testnet_1   | 
counterparty-testnet_1   | Traceback (most recent call last):
counterparty-testnet_1   |   File "/usr/local/bin/counterparty-server", line 11, in <module>
counterparty-testnet_1   |     load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
counterparty-testnet_1   |   File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
counterparty-testnet_1   |     server.main()
counterparty-testnet_1   |   File "/counterparty-cli/counterpartycli/server.py", line 166, in main
counterparty-testnet_1   |     server.start_all(db)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/server.py", line 489, in start_all
counterparty-testnet_1   |     blocks.follow(db)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1433, in follow
counterparty-testnet_1   |     new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 207, in parse_block
counterparty-testnet_1   |     raise e
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 201, in parse_block
counterparty-testnet_1   |     parse_tx(db, tx)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 147, in parse_tx
counterparty-testnet_1   |     raise exceptions.ParseTransactionError("%s" % e)
counterparty-testnet_1   | counterpartylib.lib.exceptions.ParseTransactionError: 'apsw.Connection' object has no attribute 'execute'
```

**Comment by jdogresorg** [comment]
Issue / Lock (ISSUELOCKC) - OK
https://testnet.xchain.io/tx/61e2bd6c752eac1faf14776b87fed3d8893abfa137fb1fc2eac273060193417d

Issue / Transfer (ISSUEXFERC) - OK
https://testnet.xchain.io/tx/0759750d632ea4ddca840ab24a9927ab0792c13c678dc8668beaaa3dba732ddd

Issue / Lock / Transfer (XFERTESTC) - OK
https://testnet.xchain.io/tx/ee0ca2baa871971f4ee7019da45e7a37e8e8c39cad49c9178d5a7cc4b60fa11b

Issue token (RESETLOCKA) - OK
https://testnet.xchain.io/tx/0259cf37ec4d8bb8efb07b2c5d1dfdd3149fe61aaaa3fa46e7c562528ba951ed

Reset / Lock (RESETLOCKA) - OK - but only destroy and lock showing up in console... no issuance
https://testnet.xchain.io/tx/8dbd8b0c244e8364477b978ac1afc238205254af1a55222b988a98e7780f9dec


```
counterparty-testnet_1   | [2022-08-23 17:24:57][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 100 of indivisible asset ISSUELOCKC (61e2bd6c752eac1faf14776b87fed3d8893abfa137fb1fc2eac273060193417d) [valid]
counterparty-testnet_1   | [2022-08-23 17:24:57][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt locked asset ISSUELOCKC (61e2bd6c752eac1faf14776b87fed3d8893abfa137fb1fc2eac273060193417d) [valid]
...
counterparty-testnet_1   | [2022-08-23 17:38:55][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 100 of indivisible asset ISSUEXFERC (0759750d632ea4ddca840ab24a9927ab0792c13c678dc8668beaaa3dba732ddd) [valid]
counterparty-testnet_1   | [2022-08-23 17:38:55][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt transfered asset ISSUEXFERC to tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 (0759750d632ea4ddca840ab24a9927ab0792c13c678dc8668beaaa3dba732ddd) [valid]
...
counterparty-testnet_1   | [2022-08-23 18:28:29][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 1.0 of divisible asset XFERTESTC (ee0ca2baa871971f4ee7019da45e7a37e8e8c39cad49c9178d5a7cc4b60fa11b) [valid]
counterparty-testnet_1   | [2022-08-23 18:28:29][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt locked asset XFERTESTC (ee0ca2baa871971f4ee7019da45e7a37e8e8c39cad49c9178d5a7cc4b60fa11b) [valid]
counterparty-testnet_1   | [2022-08-23 18:28:29][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt transfered asset XFERTESTC to tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 (ee0ca2baa871971f4ee7019da45e7a37e8e8c39cad49c9178d5a7cc4b60fa11b) [valid]
...
counterparty-testnet_1   | [2022-08-23 17:44:16][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 100.0 of divisible asset RESETLOCKA (0259cf37ec4d8bb8efb07b2c5d1dfdd3149fe61aaaa3fa46e7c562528ba951ed) [valid]
...
counterparty-testnet_1   | [2022-08-23 18:21:49][INFO] Destruction: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt destroyed 10000000000 RESETLOCKA with tag ‘reset’(8dbd8b0c244e8364477b978ac1afc238205254af1a55222b988a98e7780f9dec) [valid]
counterparty-testnet_1   | [2022-08-23 18:21:49][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt locked asset RESETLOCKA (8dbd8b0c244e8364477b978ac1afc238205254af1a55222b988a98e7780f9dec) [valid]

```

**Comment by jdogresorg** [comment]
- Issue token with supply (RESETLOCKB) - OK
https://testnet.xchain.io/tx/8d9437b9503a713f7bdc52c76a4dd00aba050c202011b92b3bd07b77a86b2b7f

- Reset / Lock (RESETLOCKB) - ???
https://testnet.xchain.io/tx/6336d5d348929eaea5d5662345813b5bc7197db5f2c2903a5427886befc09405

```
counterparty-testnet_1   | [2022-08-23 18:50:43][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 100.0 of divisible asset RESETLOCKB (8d9437b9503a713f7bdc52c76a4dd00aba050c202011b92b3bd07b77a86b2b7f) [valid]
...
counterparty-testnet_1   | [2022-08-23 18:55:40][INFO] Destruction: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt destroyed 10000000000 RESETLOCKB with tag ‘reset’(6336d5d348929eaea5d5662345813b5bc7197db5f2c2903a5427886befc09405) [valid]
counterparty-testnet_1   | [2022-08-23 18:55:40][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 100 of indivisible asset RESETLOCKB (6336d5d348929eaea5d5662345813b5bc7197db5f2c2903a5427886befc09405) [valid]
counterparty-testnet_1   | [2022-08-23 18:55:40][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt locked asset RESETLOCKB (6336d5d348929eaea5d5662345813b5bc7197db5f2c2903a5427886befc09405) [valid]
```

**Comment by jdogresorg** [comment]
- Issue token with no supply (RESETLOCKC) - OK
https://testnet.xchain.io/tx/dcb453b37daa6869518e8ae90b01b7be72f17714219eeecf11e0e4a7cc32576e

- Reset / Lock (RESETLOCKC) - FAIL - Ignored completely.. nothing shows up in error log
https://testnet.xchain.io/tx/ccf3a400cd7785e2094fcdeef04b2e6c1f796e42462636b7ea96f2e9277cec69

```
counterparty-testnet_1   | [2022-08-23 18:50:43][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt created 0.0 of divisible asset RESETLOCKC (dcb453b37daa6869518e8ae90b01b7be72f17714219eeecf11e0e4a7cc32576e) [valid]
...
Nothing shows up in console for reset/lock tx

```

**Comment by jdogresorg** [comment]
- Issue token with no supply (RESETLOCKD) - OK
https://testnet.xchain.io/tx/fb2255f163eacbb7ed85414c518bddb23acc57db79621acb427b5b478a6f38ca

- Reset token and issue 100 supply (RESETLOCKD) - FAIL - Ignored completely
https://testnet.xchain.io/tx/32e5ec804786fef89cf89f4392f6aca6ef238851d205b1ff9266cda7135dbf07

Seems that we have an issue with being able to `reset` supply on assets with no supply issued. The `reset` transactions are completely ignored by counterparty-lib.

**Comment by jdogresorg** [comment]
Segwit/Subasset Testing - ISSUETEST - tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4
---

- Issue 1.00000000 ISSUETEST.A tokens - OK
https://testnet.xchain.io/tx/9bebc79714e9383e3b8705de29b1870a4d9bb8f40b298d1388e873ca3638d4e2

- Reset supply to 1 ISSUETEST.A tokens - OK
https://testnet.xchain.io/tx/9498e97853d6bf3477c8fdff3ac461d1f40b7b4e01d5fc79499ff9afab10e8ee

- Transfer ownership to new address (normal) - OK
https://testnet.xchain.io/tx/ef2b0fd63e915ba4925edca52a0b1b108d2879fb087cd1e62f04d03260e436d4

- Transfer ownership back to original address (segwit) - OK
https://testnet.xchain.io/tx/9ef6f366f9d9bdefd2bf85f2910b8800e6a855d2a6d2845e1e6ae13e038d4b0e

- Lock with "lock" param - OK
https://testnet.xchain.io/tx/7172c00f5f0ef1539c5da2f0bb696d70978b26e9d76473fdb44d64098ee555c9

- Issue 1 ISSUETEST.B tokens - OK
https://testnet.xchain.io/tx/25e7224835e43913d3dc1340f0e1faf69f3663d224935cb1d21fe6822dc1ede7

- Reset supply to 100.00000000 ISSUETEST.B tokens - OK
https://testnet.xchain.io/tx/70a17bc03470e8582229ff346dfd735e7c7da48ccd1eef22b7567ea8345f032d

- Lock with "LOCK" asset description - OK
https://testnet.xchain.io/tx/e489c068bf301db5b1cac435bf906a1f0846c1a53b8dfe03cad3ae5dda59d450


```
counterparty-testnet_1   | [2022-08-23 23:01:04][INFO] Subasset Issuance: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 created 1.0 of divisible subasset ISSUETEST.A as numeric asset A6787543521062296561 (9bebc79714e9383e3b8705de29b1870a4d9bb8f40b298d1388e873ca3638d4e2) [valid]
...
counterparty-testnet_1   | [2022-08-23 23:13:36][INFO] Destruction: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 destroyed 100000000 A6787543521062296561 with tag ‘reset’(9498e97853d6bf3477c8fdff3ac461d1f40b7b4e01d5fc79499ff9afab10e8ee) [valid]
counterparty-testnet_1   | [2022-08-23 23:13:36][INFO] Subasset Issuance: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 created 100 of indivisible subasset ISSUETEST.A as numeric asset A6787543521062296561 (9498e97853d6bf3477c8fdff3ac461d1f40b7b4e01d5fc79499ff9afab10e8ee) [valid]
...
counterparty-testnet_1   | [2022-08-23 23:39:04][INFO] Issuance: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 transfered asset A6787543521062296561 to mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt (ef2b0fd63e915ba4925edca52a0b1b108d2879fb087cd1e62f04d03260e436d4) [valid]
...
counterparty-testnet_1   | [2022-08-23 23:47:06][INFO] Issuance: mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt transfered asset A6787543521062296561 to tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 (9ef6f366f9d9bdefd2bf85f2910b8800e6a855d2a6d2845e1e6ae13e038d4b0e) [valid]
...
counterparty-testnet_1   | [2022-08-24 00:00:32][INFO] Issuance: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 locked asset A6787543521062296561 (7172c00f5f0ef1539c5da2f0bb696d70978b26e9d76473fdb44d64098ee555c9) [valid]
...
counterparty-testnet_1   | [2022-08-23 23:13:36][INFO] Subasset Issuance: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 created 1 of indivisible subasset ISSUETEST.B as numeric asset A264336431422731521 (25e7224835e43913d3dc1340f0e1faf69f3663d224935cb1d21fe6822dc1ede7) [valid]
...
counterparty-testnet_1   | [2022-08-23 23:39:04][INFO] Destruction: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 destroyed 1 A264336431422731521 with tag ‘reset’(70a17bc03470e8582229ff346dfd735e7c7da48ccd1eef22b7567ea8345f032d) [valid]
counterparty-testnet_1   | [2022-08-23 23:39:04][INFO] Subasset Issuance: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 created 100.0 of divisible subasset ISSUETEST.B as numeric asset A264336431422731521 (70a17bc03470e8582229ff346dfd735e7c7da48ccd1eef22b7567ea8345f032d) [valid]
...
counterparty-testnet_1   | [2022-08-24 00:00:32][INFO] Issuance: tb1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2wj67a4 locked asset A264336431422731521 (e489c068bf301db5b1cac435bf906a1f0846c1a53b8dfe03cad3ae5dda59d450) [valid]

```

**Comment by jdogresorg** [comment]
Tried to reset a locked asset and got error message as expected 'cannot reset a locked asset'.

At this point CIP03 looks good to me to merge.

**Comment by droplister** [comment]
Activation Block 753,000 is only two weeks (2,145 blocks) from the time I'm posting.

I don't think that is sufficient time for the federated node network and the secondary network of servers that rely on third-party APIs like xchain.io to modify their code to support this change.

Recommend merging with an activation block a little further in the future to mitigate the risk to state management this change represents.

1 ASSET could become 0.00000001 ASSET or vice versa and that's non-trivial to handle if you wrote code that presumes a non-divisible asset could become non-divisible later.

**Comment by jdogresorg** [comment]
There are no changes to the way that the CP API or the xchain API works in regards to getting asset balances, so I am unsure what changes your expecting 3rd party devs to make.

**Comment by jotapea** [comment]
@droplister @jdogresorg Counterparty developers should not be obligated to consume its data only through the API (even less a private entity). I have found reading the SQLite tables [directly](https://github.com/CNTRPRTY/xcpdev/blob/bea8175a236fac53271f7b94645913b6ef406d08/express_server/src/index.js#L16) to be better, as the API is very inefficient. A problem made worse with the introduction of issuance resets.

**Pull request merged**
