### PR TITLE
9.60.3 release

### PR DESCRIPTION
**Pull request by jdogresorg**
- Bumped bitcoin core version to 24.1
- Adjusted DEFAULT_MULTISIG_DUST_SIZE (7800->1000)
- Fixed issue with oracle function returning bad values
- Fixed issue with change smaller than DUST throwing error
- Fixed issue with issuances and callability error
- Fixed issue with issuance backwards compatability
- Fixed issue with dividends not working on reset assets
- Redefined EMPTY address to mean no XCP or BTC history
- Fixed issue with skipping owner validation on numeric issuances
- Fixed issue with sweeps not transferring asset ownership if no supply issued
- Added origin field to dispensers (allows refill/close/reopen from `origin`)
- Added support for triggering dispenses on all tx outputs
- Added max dispense limit of 1000

## Notes
Mainnet activation block is set to 825,000 for all protocol_changes in this release. Need to update release to set activation blocks 2 weeks out from release date, once closer to release.

### CODE REVIEW

**Comment by jotapea** [comment]
@jdogresorg @pataegrillo Are you the only 2 people deciding what goes into the next release and at what activation block? If not, can you let me know what process is being followed?

As both of you know I am running a counterparty-lib node for xcp.dev and bitSTART, so this is very relevant to me. So, I ask to please remove the activation block, and lets have a conversation IN THIS REPO about what the consensus is for the next release...

**Comment by jdogresorg** [comment]
> @jdogresorg @pataegrillo Are you the only 2 people deciding what goes into the next release and at what activation block? 

No, Javier and I are not the only ones making decisions, as always, conversations with the dev community take place on tweaks, improvements, and updates before any code changes are made. These conversations take place on the forums, telegram, and github, however most of the conversations happen in telegram dev channel (which you were a member of at one point, until you choose to leave).

> If not, can you let me know what process is being followed?

The majority of the updates in this release are fixing issues which have been open for well over a year, with plenty of time for discussions, review, proposed solutions, etc. You can feel free to review all the merged pull requests, closed issues, and github discussions in the last few weeks to get an overview of what has been happening in dev. 

> please remove the activation block, and lets have a conversation IN THIS REPO about what the consensus is for the next release...

Activation blocks are chosen at time of release and historically have been set to activate 2 weeks after release… this release will be no different and activation blocks will be chosen at the time of the release.... 825,000 is simply a placeholder block, not the true activation block, as indicated in the pull request notes.

I once again encourage you to join the CP Dev channel on telegram so that your kept up to speed on CP developments.

https://t.me/Counterparty_Dev

**Comment by jotapea** [comment]
I don't consider the https://t.me/Counterparty_Dev chat as the place to have conversations about the next release. See https://github.com/CounterpartyXCP/cips/discussions/97.

@jdogresorg, your answer is basically a long way of saying: "I am in control, but let me write down my canned answers". You keep repeating phrases like "conversations happens everywhere by the community" and "the changes are in the repo for months to review"...

My gut feeling is that the main problem is $$$ and incentives. For some reason, "the community" decided to delegate development to a single person asking for full-time funding. Then, these people have already given you money, so of course they will not change their stance of removing you from being in charge, as that will mean they "wasted" their money by giving it to you in the first place. Then, @pataegrillo is paid to develop stuff, which he is being told to work on (not decided by him), then this development is "done" and accepted to the repo by the same person giving the orders. Then, is just about "waiting" and it fits perfectly into your "has been done for months" can. Incentives are completely messed up!

@jpja @wasthatawolf @pataegrillo please let me know who else is involved in the repository privileges and access. Jeremy has continuously shown he is unable (or maybe just unwilling) to have transparent open involvement of other members of the federated network have a say in how the protocol advances.

**Comment by loon3** [comment]
the problem here is that you tend to resort immediately to personal attacks when things aren't going the way you imagine they should, its not constructive

if you'd like to discuss any issues you have with this release then go ahead and leave your comments here on this PR, seems appropriate as long as you're discussing the PR itself and not some broader issue you seem to have with the way development of counterparty is conducted

**Comment by jotapea** [comment]
Well that is what I am trying to do, and I am explaining my thinking. If I am wrong in anything I said, please specify.

Do you realize that the "personal attacks" phrasing itself is an attack? And this has happened before from you and Jeremy since I started getting involved and giving my feedback AS A DEVELOPER.

But actually, thanks for the message. As it shows here in the repo the type of response I was getting from the https://t.me/Counterparty_Dev chat, and why I had to decide not to support that status quo.

**Comment by loon3** [comment]
I apologize if you took offense to me saying "personal attack".  That's not constructive either.

You're correct in regard to incentives, anyone working on building out the protocol is more incentivized to work on their own ideas or things that they think need to be fixed.  But you're not correct in terms of two people controlling the development process.  Jeremy and Javier do not work in a vacuum and there are many stakeholders (ie asset holders, anyone building on the platform, etc.).  Could the process be better?  Sure!  But from what I can tell Jeremy and Javier are thoughtful and take input from everyone and for the most part this process works.

**Comment by jotapea** [comment]
What I see here is the status quo saying: "things work fine the way they are".

Then, I'm saying: "things are not working for me and my products".

Where does this leave us? What can be done to move forward in agreement?

My suggestion would be to NOT have a single person doing everything related to the next release, starting with the merges to master and listing the ["planned"](https://github.com/CounterpartyXCP/counterparty-lib/pull/1256#issue-1905529491) release itself.

Where is the place IN THIS REPO where these "plans" are discussed? Not being able to point to a place in the protocol repository is not acceptable. Maybe it was at one point, but it no longer is.

I am a stakeholder and I am speaking up in the place I believe is the most appropriate to do so, which for the next release is in this thread.

**Comment by jdogresorg** [comment]
> My gut feeling is that the main problem is $$$ and incentives. 

FYI, the community has not donated to cover my dev salary since 2022, so I continue to work on CP for the past year on my own dime because I enjoy it and want to see the protocol push forward. No other reasons. 

> Then, I'm saying: "things are not working for me and my products".

If there is something which is not working, please create a github issue and we will look into it. Please specifically mention what WAS working and is no longer working, and how it is directly effecting your "product" negatively.

I believe this is NOT a case of things not working for you and your products, but rather a design path you would prefer that Counterparty follow, and when your design decisions are not agreed with by the larger community, you get upset and become hostile. This has been the case for the past 2 years, where you consistently advocate against ANY updates except your own (including simple bitcoin core version updates).  

> Where is the place IN THIS REPO where these "plans" are discussed? 

This has been asked and answered already in this thread... specifically "These conversations take place on the forums, telegram, and github, however most of the conversations happen in telegram dev channel". 

>My suggestion would be to NOT have a single person doing everything related to the next release, starting with the merges to master and listing the https://github.com/CounterpartyXCP/counterparty-lib/pull/1256#issue-1905529491 release itself.

The suggestion to use `develop` instead of `master` is good. To date, I have simply been following the same software release process that John Villar established 5+ years ago. However I do agree with you that merging to `develop` and eventually to `master` is a much more clean process. I will work with Javier to migrate development to the `develop` branch for the next 9.61.0 release.

**Comment by jotapea** [comment]
Before continuing with the conversation, I want to apologize for my tone in my first messages on this thread. Maybe this is the reason why we started leaning into charged characterizations instead of focusing on the topic. I might have actually started it, so it is my bad. But you must understand it has become quite frustrating for me to deal with an establishment that has obvious grasps on control.

But like @wasthatawolf says, lets be productive here.

@jdogresorg Why can't you just do the `develop` branch changes from this moment? There is no reason to wait. Master should be the last stable release, not a work in progress.

And I have some other suggestions I think we can agree on.

- Can we change the title of this thread to "v9.60.3 release discussion", to show this is a shared decision by the federated nodes?
- Can links be added to the list of changes you @jdogresorg are proposing for the next release? As you know I have already given my input in some of them, but I would like to take a look to as many of these as I can...

I'm ok with a release soon if it focuses only on fixes (like v9.60.2 was), but not so much for protocol changing ones like the new issuance message ids. Any protocol changing release should include more reviews, agreement and coordination. And it should be minor version update (v9.61) instead of a revision (v9.60.X).

**Comment by Jpja** [comment]
I feel we need a Process CIP for how protocol updates should be decided and rolled out.

First, define kinds of updates
- hot fix (critical bug, immediately release, node operators assumed to verify the code and upgrade asap)
- issue (no tradeoffs, not very urgent, add to general updates and give weeks to review)
- CIP (new feature with tradeoffs, must prove real demand for it)

Second, specify the decision process for each kind of update.

Third, formulate the process. Make it so that more people get involved. Like a newsletter where it's explained in non-technical terms, a recorded twitter space, etc).

This is a rough outline. Would like a real document. Maybe something we can copy from another project?

For 9.60.3 specifically I see @jdogresorg and @pataegrillo have done a HUGE job, fixed a lot of issues. They deserve a lot of credit for their work. Also @jotapea and other have been involved in discussions and given serious feedback. Definitively spent a lot of time and effort, especially in the [CIP 31 - file encoding](https://github.com/CounterpartyXCP/cips/discussions/109) discussion.

Jotpea and @keyuno convinced me that DB optimization is the better option. Thus I am against implementing CIP 31, or at least give some time to write up an alternative CIP. I also advice against [batch dispensers](https://github.com/CounterpartyXCP/counterparty-lib/issues/1148). Can lead to DB bloat unless an appropriate XCP gas fee is introduced. I elaborated on this in a new thread on [gas fees](https://github.com/CounterpartyXCP/cips/discussions/123).

**Comment by jotapea** [comment]
While I agree with @Jpja's intention of formalizing the process, I believe we can also do incremental improvements to avoid disruption and resistance from the current establishment.

I believe the first concrete change that needs to happen is reverting the `master` branch to be the latest stable release, which is v9.60.2.

Then, what is currently @jdogresorg's branch for what he believes is the next update, could continue in the repo but with a different name. As I have stated, my main concern with this branch is the inclusion of protocol updates when it appears to be only about fixes.

So, [this list](https://github.com/CounterpartyXCP/counterparty-lib/pull/1256#issue-1905529491) needs to be reduced to only the fixes. Then, all protocol altering changes need to be moved to a separate v9.61 thread.

**Comment by jdogresorg** [comment]
> I believe the first concrete change that needs to happen is reverting the master branch to be the latest stable release, which is v9.60.2.

@jotapea We already have limited dev resources, and backing out all the merged PRs and merging them all to `develop` is a substantial amount of work. As I have already indicated, I am following the same development process we have been using for the past 5 years for THIS release, and will be using the `develop` branch in the NEXT release.

The next release will be out in the week or two, once Javier finishes up some additional updates.

**Comment by jotapea** [comment]
@jdogresorg Renaming a branch is not a substantial amount if work.

Your proposed v9.60.3 is not a fixes only release, it includes protocol changes that REQUIRE the federated nodes network to be updated. As you are aware, I am part of that.

Can you let me know the people involved in deciding that the release is imminent? And why the arguments mentioned in this thread are not being considered?

**Comment by jdogresorg** [comment]
Closing PR. Will open new PR for 9.61.0 when ready for release

**Comment by Jpja** [comment]
> Adjusted DEFAULT_MULTISIG_DUST_SIZE (7800->1000)

NACK. This will make it uneconomical to redeem dust. I estimate break-even for redeeming dust to drop from 63 to 8 sat/B. The default behavior should encourage redeeming dust, as this reduces the utxo set (good for bitcoin nodes, including counterparty). Even if there is still no good implementation for redeeming, the idea is that once enough dust is accumulated, bounties will be made for a solution (eg inside FreeWallet). 
_P.S. If STAMP want to bind up less dust, let it be on them, they can always override the defaults._  https://github.com/CounterpartyXCP/cips/discussions/93

> and will be using the develop branch in the NEXT release.

Great! For some historical context, `develop` branch was used the first one-two years. Back then there were several programmers, some I believe were paid. At least one founder personally donated significant amounts. Once the founders gave the project to the community (Satoshi style) we were extremely lucky to have Jdog and John Villar who did great despite no funding. We still have very little no funding .. let us never forget in heated debates that we are hobbyist doing this out of passion :)

**Comment by jotapea** [comment]
Thanks for the message @Jpja. I try to keep the conversation civil, but is not easy when it seems decisions are taken unilaterally. Why was v9.60.3 suddenly cancelled? Who were part of this decision?

My arguments are being proven with the actions taken.

I don't think accumulating too many changes in a single release is a good idea either, so why not keep this release focused on fixes everyone can agree on?

> Will open new PR for 9.61.0 when ready for release

v9.61 being a protocol changing release is a step in the right direction, but we need to agree on these protocol changes. The phrasing "when ready for release" is implying these decision have already been made.

@loon3 @jdogresorg @pataegrillo @Jpja what can we do about this situation? I have already suggested opening up a thread focused on the next protocol updating release, where we can discuss as a group what protocol changes to include.

I also want to take the opportunity to offer myself as a development resource. I can help in unwinding the merges to master that were done prematurely, and this will also be an opportunity for me to review these changes. I can help in make the v9.60.3 release happen.

**Pull request closed without merging**
