### PR TITLE
Enable API During Reparses

### PR DESCRIPTION
**Pull request by adamkrellenstein**
**Untested**

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
@deweller, can you try this out?

**Comment by adamkrellenstein** [comment]
Ah, just did some testing myself... this approach won't work.

**Comment by adamkrellenstein** [comment]
Something similar might work. The reparse would have to be completely atomic, or the database that the API connects to would have to be frozen for the duration of the reparse. (The issue is that while the reparse works through the entire history of Counterparty, the API returns *that* data, i.e. the very old data.)

**Comment by robby-dermody** [comment]
no longer necessary. closing

**Pull request closed without merging**
