### PR TITLE
custom_inputs parameter for controlling exact utxos to use in transactions

### PR DESCRIPTION
**Pull request by cryptonaut420**
expects an array of same data as retrieved by bitcoind's listunspent() function

### CODE REVIEW

**Comment by ouziel-slama** [comment]
+1!! definitely the faster way to generate a transactions! Even perhaps that should be the default mode..
(could you please make the PR on `develop` branch?)

**Comment by adamkrellenstein** [comment]
ACK

Isn't this already made against `develop`?

> expects an array of same data as retrieved by bitcoind's listunspent() function

Can that be documented in the code?

**Comment by cryptonaut420** [comment]
Yeah, the PR is to the develop branch but its coming from my master branch, mostly because I messed up and was trying not to include some other unnecessary commits lol

**Comment by ouziel-slama** [comment]
oh! sorry I misread!

**Pull request merged**
