### PR TITLE
NodeJS-style logging filter

### PR DESCRIPTION
**Pull request by rubensayshi**
NodeJS-style logging, ie:
`filters="*,-counterpartylib.lib,counterpartylib.lib.api"`

will log:
 - counterpartycli.server
 - counterpartylib.lib.api

but will not log:
 - counterpartylib.lib
 - counterpartylib.lib.backend.addrindex

-------------------

This will make it possible again to use the `--verbose` of `counterparty-server` without getting HUGE amount of spam:
`OUNTERPARTY_LOGGING="*,-counterpartylib.lib.backend.addrindex.getrawtransaction_batch" counterparty-server --testnet --verbose start`

I haven't done python for a while and before I never needed anything like this, but the NodeJS way of doing logging with a list of filters is kinda nice imo.

https://github.com/CounterpartyXCP/counterparty-cli/pull/68 provides the `console_logfilter` from `env.COUNTERPARTY_LOGGING`.

### CODE REVIEW

**Comment by robby-dermody** [comment]
utACK (we could add additional child loggers in the future on top of these basics)

@adamkrellenstein ?

**Comment by rubensayshi** [comment]
yea the `__name__` works for most stuff, but for really spammy stuff doing `_logger = logger.getChild('myspammything')` helps :)

**Comment by robby-dermody** [comment]
can we rename `NodeJSStyleLoggingFilter` to something different, like `ModuleLoggingFilter` or something more generic? Past that it looks good to me, ready to merge

**Comment by adamkrellenstein** [comment]
ACK

**Pull request merged**
