### PR TITLE
Remove use of tornado in the APIServer

### PR DESCRIPTION
**Pull request by robby-dermody**
Submitting this for consideration.

Currently `counterparty-lib` utilizes tornado improperly. It's a single-threaded implementation that requires  asynchronous handler functionality, that we use with a WSGI wrapper, which is synchronous. This is seemingly leading to a situation where I believe we effectively have a single-threaded API servicing thread, that can block anywhere the API call handler has a wait state (i.e. making an RPC call to bitcoind, database access, etc).

See:
* http://stackoverflow.com/questions/26015116/making-tornado-to-serve-a-request-on-a-separate-thread/26018742#26018742 
* https://github.com/mitsuhiko/flask/issues/986
* https://github.com/tornadoweb/tornado/wiki/Threading-and-concurrency

One solution is to take everything out to be fully non-blocking, in the spirit of using tornado. This would be fast and elegant, but require a good deal of work. The other solution is to scrap tornado, and utilize flask's `run_server` call with `threading=True`. This utilizes Python 3's `ThreadingMixIn`, present in `socketserver`, meaning that each new request are handled on a new thread. It's not at the same level of using something more "robust", like WSGI and gnuicorn, but in informal testing it appears to work alright, and I am seeing better response latency than we have now.

Potential downsides of this approach are that `run_server` is not seen as a very robust "production-level" approach, and the multiple threads can still lead to contention in the Python GIL. Given this, I see this as an intermediate stepping stone, and better than what we have currently. I don't see Python GIL deadlocking as an issue, because the vast majority of any waits between the API request threads appears to be for I/O (e.g. bitcoind query, which gives up the GIL), not due to executing Python code, or some other behavior that causes a thread to hang on to the GIL.

It's not the best test, but I've been running this code for a few days on cw01, with a simple test script that makes a call to `get_running_info` every second, and prints the result if the call takes > .2 seconds to return. From the results below, you'll notice that the results appear to be improved, but are still not perfect. I believe that there is another layer of blocking going on. Some of it is due to bitcoind itself (which I am seeing due to another script I run at the same time that hits bitcoind directly... a good amount of overlap with the delays. But some of it may possibly be at the DB level, or somewhere else, within counterparty-server itself...). This seems like a good first step though.

Here is what I get over a few runs:
```
RUN 1 - tornado (current state):
2015-10-12T16:53:31.777876, 1.20587205887
2015-10-12T16:53:36.010863, 2.22851896286
2015-10-12T16:55:04.668556, 0.261396169662
2015-10-12T16:58:38.864192, 1.22042798996
2015-10-12T16:58:42.320848, 1.2590649128
2015-10-12T17:01:34.231542, 1.16674494743
2015-10-12T17:01:36.705037, 1.47248411179
2015-10-12T17:03:44.793070, 1.57112789154
2015-10-12T17:03:47.340858, 1.54669094086
2015-10-12T17:03:49.471430, 1.12947702408
2015-10-12T17:08:51.792288, 0.916256904602
2015-10-12T17:08:53.211869, 0.418492078781
2015-10-12T17:08:55.299165, 1.08619499207
2015-10-12T17:13:32.961172, 1.2023639679
2015-10-12T17:13:35.441769, 1.47950291634
2015-10-12T17:13:57.793943, 1.19525909424
2015-10-12T17:13:59.066954, 0.271912097931
2015-10-12T17:14:01.167586, 1.09953093529
2015-10-12T17:15:12.712869, 0.270159006119
2015-10-12T17:18:41.515881, 2.81734895706
2015-10-12T17:18:44.282316, 0.761437177658
2015-10-12T17:19:02.802910, 1.47165799141
2015-10-12T17:19:05.957270, 0.997284889221
2015-10-12T17:23:51.670528, 0.704379081726
2015-10-12T17:23:54.167703, 1.49608612061
2015-10-12T17:24:07.809377, 1.60003709793
2015-10-12T17:24:10.926219, 1.00057196617
2015-10-12T17:28:04.946306, 1.15994715691
2015-10-12T17:28:59.109651, 0.820230007172
2015-10-12T17:29:01.590969, 1.48020792007
2015-10-12T17:29:12.815072, 1.19177889824
2015-10-12T17:29:15.879983, 0.997329950333
2015-10-12T17:34:17.808663, 1.67508006096
2015-10-12T17:34:19.030029, 0.220273017883
2015-10-12T17:34:21.042653, 1.01237893105
2015-10-12T17:34:30.822006, 0.732206821442
2015-10-12T17:34:33.334441, 1.51134705544
2015-10-12T17:35:20.720420, 0.226918935776
2015-10-12T17:39:23.977047, 2.13216209412
2015-10-12T17:39:25.189968, 0.211834907532
2015-10-12T17:39:27.682921, 1.49182915688
2015-10-12T17:44:29.785363, 1.78232598305
2015-10-12T17:44:32.964072, 1.04844689369
2015-10-12T17:49:34.798163, 1.58253693581
2015-10-12T17:49:39.123401, 2.17623806
2015-10-12T17:54:42.062957, 1.69303894043
2015-10-12T17:54:44.841789, 1.7782330513
2015-10-12T17:55:29.205274, 0.206427097321
2015-10-12T17:59:46.841493, 1.66656804085
2015-10-12T17:59:50.010376, 1.02724814415
2015-10-12T18:01:29.837017, 0.350666046143
2015-10-12T18:04:51.795354, 1.13921403885
2015-10-12T18:04:53.071345, 0.274899959564
2015-10-12T18:04:55.236950, 1.16450715065
2015-10-12T18:09:57.823019, 1.39600300789
2015-10-12T18:09:59.098726, 0.274605035782
2015-10-12T18:10:01.147721, 1.04790091515
2015-10-12T18:11:22.360754, 0.93248295784
2015-10-12T18:15:02.789394, 1.61359095573
2015-10-12T18:15:04.102587, 0.312100887299
2015-10-12T18:15:06.229105, 1.12542080879
2015-10-12T18:19:14.524541, 0.327974081039
2015-10-12T18:20:08.848463, 1.14570999146
2015-10-12T18:20:10.141766, 0.292201042175
2015-10-12T18:20:12.432678, 1.28980493546
2015-10-12T18:25:14.768896, 1.11332988739
2015-10-12T18:25:16.098623, 0.328629970551
2015-10-12T18:25:18.350721, 1.25101113319
2015-10-12T18:30:20.815074, 1.24271917343
2015-10-12T18:30:25.342944, 2.41682505608
2015-10-12T18:35:27.802182, 1.30229902267
2015-10-12T18:35:31.038405, 1.09946894646
2015-10-12T18:35:45.313081, 0.231995820999
2015-10-12T18:40:34.018157, 1.58798599243
2015-10-12T18:40:37.125490, 0.913027048111
2015-10-12T18:43:13.790393, 1.02282691002
2015-10-12T18:45:40.033817, 1.66009306908
2015-10-12T18:45:42.859302, 1.82439899445
2015-10-12T18:50:44.792203, 1.64864015579
2015-10-12T18:50:47.243327, 1.45002293587
2015-10-12T18:50:49.515708, 1.27126502991
2015-10-12T18:55:51.784764, 1.03963494301
2015-10-12T18:55:53.392342, 0.606486082077
2015-10-12T18:55:56.183619, 1.79017019272
2015-10-12T19:00:59.020408, 1.58180189133
2015-10-12T19:01:02.125507, 1.03664112091
2015-10-12T19:06:04.864015, 1.41823506355
2015-10-12T19:06:06.076560, 0.211812019348
2015-10-12T19:06:08.567819, 1.4901599884
2015-10-12T19:06:56.973879, 1.19815897942
2015-10-12T19:11:00.146049, 0.222491979599
2015-10-12T19:11:10.808154, 1.61753606796
2015-10-12T19:11:13.860152, 0.933480978012
2015-10-12T19:16:15.791506, 1.52866387367
2015-10-12T19:16:19.197658, 1.27268886566
2015-10-12T19:16:20.820503, 0.621752977371
2015-10-12T19:21:21.780803, 1.76364707947
2015-10-12T19:21:24.715956, 0.931003093719
2015-10-12T19:26:26.765792, 1.53881192207
2015-10-12T19:26:29.738140, 0.96790599823
2015-10-12T19:31:08.045407, 0.238597869873
2015-10-12T19:31:31.835850, 1.59019494057
2015-10-12T19:31:36.051868, 2.20906019211
2015-10-12T19:36:10.410934, 0.237576007843
2015-10-12T19:36:38.974086, 1.48106980324
  15-10-12T19:36:41.895925, 0.917368888855
‚ñΩ5-10-12T19:41:43.768597, 1.49860191345
2015-10-12T19:41:48.409150, 2.49380493164
2015-10-12T19:46:50.818321, 1.26228880882
2015-10-12T19:46:53.657137, 1.83772301674
2015-10-12T19:51:55.781835, 1.77139687538
2015-10-12T19:51:58.656034, 0.870363950729
2015-10-12T19:54:11.640708, 0.541156053543
2015-10-12T19:57:00.831799, 1.46867990494
2015-10-12T19:57:03.704984, 0.868633985519
2015-10-12T20:01:20.168967, 0.421679973602
2015-10-12T20:02:05.861764, 1.50099802017
2015-10-12T20:02:08.798776, 0.932537078857
2015-10-12T20:06:21.919813, 0.237859010696
2015-10-12T20:07:10.777048, 1.71036314964
2015-10-12T20:07:13.760002, 0.977967023849
2015-10-12T20:12:15.763701, 1.78983020782
2015-10-12T20:12:18.747357, 0.97917509079
2015-10-12T20:12:25.848852, 1.08453011513
2015-10-12T20:15:10.825029, 0.33349108696
2015-10-12T20:16:26.255421, 0.203073978424
2015-10-12T20:17:20.789252, 1.37494802475
2015-10-12T20:17:24.459642, 1.64450216293
2015-10-12T20:22:26.840252, 1.17053508759
2015-10-12T20:22:29.659189, 1.81784009933
2015-10-12T20:23:32.188595, 1.23180389404
2015-10-12T20:27:31.766398, 1.64644217491
2015-10-12T20:27:34.531443, 1.76394891739
2015-10-12T20:32:36.821008, 1.08017206192
2015-10-12T20:32:39.625745, 1.80364894867
2015-10-12T20:34:37.503227, 0.325752973557
2015-10-12T20:35:12.918550, 0.27904009819
2015-10-12T20:37:41.774787, 1.39775514603
2015-10-12T20:37:44.764651, 0.98529791832
2015-10-12T20:42:46.778214, 0.981850147247
2015-10-12T20:42:49.550877, 1.77155900002
2015-10-12T20:45:35.219551, 0.884603023529
2015-10-12T20:47:51.755312, 1.1206870079
2015-10-12T20:47:54.516461, 1.76005887985
2015-10-12T20:48:19.462062, 1.33108711243
2015-10-12T20:52:56.781119, 1.30239105225
2015-10-12T20:52:59.700715, 0.915014028549


RUN 1 - flask (this PR):
2015-10-12T22:54:56.335918, 0.276360988617
2015-10-12T22:54:57.541750, 0.204766988754
2015-10-12T23:00:02.705538, 0.223665952682
2015-10-12T23:04:28.887703, 0.278452157974
2015-10-12T23:05:07.601669, 0.217483997345
2015-10-12T23:05:09.946471, 0.25156211853
2015-10-12T23:10:12.819528, 0.249075889587
2015-10-12T23:13:36.489470, 0.426218986511
2015-10-12T23:15:16.349661, 0.355546951294
2015-10-12T23:15:17.563820, 0.213068008423
2015-10-12T23:20:22.552086, 0.204680919647
2015-10-12T23:20:24.901945, 0.268810033798
2015-10-12T23:30:31.957008, 0.267292976379
2015-10-12T23:30:33.324049, 0.365953922272
2015-10-12T23:30:35.552859, 0.20658493042
2015-10-12T23:35:36.377635, 0.235035181046
2015-10-12T23:35:37.584943, 0.206233024597
2015-10-12T23:35:39.928402, 0.256330966949
2015-10-12T23:40:35.226372, 0.580222129822
2015-10-12T23:40:42.599794, 0.24486207962
2015-10-12T23:45:49.934935, 0.24737906456
2015-10-12T23:47:38.036356, 0.410390138626
2015-10-12T23:50:52.599399, 0.248419046402
2015-10-12T23:50:54.856030, 0.210711956024
2015-10-12T23:54:51.458979, 0.261743068695
2015-10-12T23:55:57.067363, 0.260165929794
2015-10-12T23:57:51.274463, 0.216327190399
2015-10-13T00:01:02.657733, 0.312313079834
2015-10-13T00:01:04.933490, 0.213027000427
2015-10-13T00:06:07.807560, 0.230455160141
2015-10-13T00:06:10.094542, 0.280200958252
2015-10-13T00:11:11.340581, 0.383444070816
2015-10-13T00:11:12.559393, 0.217730045319
2015-10-13T00:11:14.860522, 0.20885181427
2015-10-13T00:15:11.876539, 0.755437850952
2015-10-13T00:16:20.750523, 0.262983083725
2015-10-13T00:22:18.885868, 0.535101890564
2015-10-13T00:26:27.547675, 0.209306001663
2015-10-13T00:31:32.847713, 0.203840970993
2015-10-13T00:31:34.250606, 0.401818037033
2015-10-13T00:31:35.526938, 0.275254011154
2015-10-13T00:32:50.219065, 0.308319091797
2015-10-13T00:34:24.077294, 0.310842037201
2015-10-13T00:34:25.306613, 0.228243112564
2015-10-13T00:34:29.990243, 0.228286981583
2015-10-13T00:34:54.642668, 0.350444078445
2015-10-13T00:34:58.240293, 0.211138010025
2015-10-13T00:35:06.488020, 0.318057060242
2015-10-13T00:35:08.800068, 0.305882930756
2015-10-13T00:35:11.224238, 0.238419055939
2015-10-13T00:35:12.592044, 0.366726875305
2015-10-13T00:35:14.974628, 0.37574505806
2015-10-13T00:35:16.698166, 0.723390102386
2015-10-13T00:35:18.945055, 0.240135192871
2015-10-13T00:35:21.342563, 0.209280967712
2015-10-13T00:35:22.731364, 0.387724876404
2015-10-13T00:35:24.063214, 0.330775976181
2015-10-13T00:35:28.410832, 1.01672506332
2015-10-13T00:35:29.801751, 0.389851093292
2015-10-13T00:35:31.411640, 0.608808994293
2015-10-13T00:35:32.779281, 0.36656498909
2015-10-13T00:35:37.119685, 1.03931593895
2015-10-13T00:35:38.423656, 0.302900791168
2015-10-13T00:35:39.627459, 0.203570842743
2015-10-13T00:35:42.619677, 0.827023983002
2015-10-13T00:35:43.957354, 0.336603879929
2015-10-13T00:35:45.581725, 0.62327003479
2015-10-13T00:35:47.695967, 1.11400318146
2015-10-13T00:35:50.141279, 0.254712820053
2015-10-13T00:35:51.664118, 0.521759986877
2015-10-13T00:35:52.901652, 0.236459970474
2015-10-13T00:35:54.134368, 0.231645107269
2015-10-13T00:35:55.669004, 0.533560037613
2015-10-13T00:36:13.061476, 0.313323974609
2015-10-13T00:36:14.297571, 0.235006093979
2015-10-13T00:36:17.810939, 0.207551002502
2015-10-13T00:36:22.529381, 0.220434904099
2015-10-13T00:36:43.313558, 0.481997966766
2015-10-13T00:36:48.168301, 0.365200996399
2015-10-13T00:36:57.211854, 1.10024118423
2015-10-13T00:36:59.581631, 0.362094163895
2015-10-13T00:37:04.239598, 0.251418828964
2015-10-13T00:37:07.450668, 1.20421099663
2015-10-13T00:37:09.710962, 0.253336906433
2015-10-13T00:37:10.988708, 0.276654005051
2015-10-13T00:37:12.216944, 0.227151155472
2015-10-13T00:37:13.488332, 0.270306825638
2015-10-13T00:37:14.817395, 0.327970981598
2015-10-13T00:37:19.131850, 0.988840818405
2015-10-13T00:37:20.491977, 0.359050035477
2015-10-13T00:37:22.103682, 0.610612869263
2015-10-13T00:37:23.406829, 0.302073001862
2015-10-13T00:37:27.812889, 1.04527187347
2015-10-13T00:37:29.140276, 0.326315164566
2015-10-13T00:37:30.372043, 0.230695009232
2015-10-13T00:37:31.619887, 0.246767997742
2015-10-13T00:37:33.686957, 1.06599497795
2015-10-13T00:37:35.904427, 1.21639585495
2015-10-13T00:37:37.487007, 0.581480026245
2015-10-13T00:37:38.784871, 0.29679107666
2015-10-13T00:37:41.184162, 0.230108976364
2015-10-13T00:37:42.681370, 0.496130943298
2015-10-13T00:37:43.899804, 0.217350959778
2015-10-13T00:37:46.566148, 0.482609987259
2015-10-13T00:37:49.814199, 0.232517004013
2015-10-13T00:41:53.566906, 0.956076145172
2015-10-13T00:41:54.873128, 0.305432081223
2015-10-13T00:46:14.953167, 0.611207008362
2015-10-13T00:46:57.613292, 0.2438621521
2015-10-13T00:46:59.889377, 0.200133085251
2015-10-13T00:49:38.238263, 0.411154985428
2015-10-13T00:52:01.350512, 0.338806867599
2015-10-13T00:52:02.630325, 0.278733968735
2015-10-13T00:57:09.120951, 0.385451078415
2015-10-13T00:58:58.929504, 0.977944135666
2015-10-13T01:02:11.343814, 0.3897960186
2015-10-13T01:12:23.154406, 0.325609922409
2015-10-13T01:17:30.438192, 0.203978061676
2015-10-13T01:20:03.770225, 0.542661905289
2015-10-13T01:22:32.756003, 0.203281879425
2015-10-13T01:22:34.123544, 0.366465091705
2015-10-13T01:27:37.025221, 0.204132080078
2015-10-13T01:32:41.344409, 0.370837926865
2015-10-13T01:32:42.657760, 0.312267065048
2015-10-13T01:36:07.224210, 0.221543073654
2015-10-13T01:37:48.221647, 0.302268028259
2015-10-13T01:37:50.457005, 0.228356838226
2015-10-13T01:47:57.534130, 0.207010984421
2015-10-13T01:47:59.797164, 0.208781003952
2015-10-13T01:53:02.601882, 0.245730876923
2015-10-13T01:53:05.530608, 0.915594100952
2015-10-13T01:55:59.901124, 0.476384878159
2015-10-13T01:58:09.175929, 0.321297883987
2015-10-13T01:58:11.437743, 0.24237203598
2015-10-13T02:03:12.367952, 0.256814002991
2015-10-13T02:03:16.844862, 0.269815921783
2015-10-13T02:11:51.314319, 0.317938089371
2015-10-13T02:18:31.376584, 0.203382015228
2015-10-13T02:23:32.333790, 0.302680969238
2015-10-13T02:23:33.541444, 0.206578969955
2015-10-13T02:23:35.832550, 0.216150045395
2015-10-13T02:28:40.101105, 0.371824026108
2015-10-13T02:33:42.340986, 0.375371217728
2015-10-13T02:33:45.845659, 0.211086988449
2015-10-13T02:38:48.759936, 0.2095079422
2015-10-13T02:43:54.167258, 0.263716936111
2015-10-13T02:43:56.374923, 0.201471805573
2015-10-13T02:45:12.376495, 0.571877002716
2015-10-13T02:54:06.519418, 0.774662017822
2015-10-13T03:03:43.982677, 0.776010990143
2015-10-13T03:04:13.333967, 0.20162320137
2015-10-13T03:04:14.556054, 0.221010923386
2015-10-13T03:07:41.740319, 0.850784063339
2015-10-13T03:09:19.578358, 0.206799030304
2015-10-13T03:09:21.854424, 0.220762968063
2015-10-13T03:14:26.136593, 0.377100944519
2015-10-13T03:19:28.342977, 0.280617952347
2015-10-13T03:19:29.616102, 0.272719144821
2015-10-13T03:19:32.618221, 0.97062587738
2015-10-13T03:29:40.763613, 0.226957082748
2015-10-13T03:29:42.137228, 0.372522830963
2015-10-13T03:34:44.323014, 0.375209093094
2015-10-13T03:34:47.795090, 0.214437007904
2015-10-13T03:39:05.468328, 0.300758838654
2015-10-13T03:39:51.211457, 0.332353830338
2015-10-13T03:39:53.425479, 0.205915927887
2015-10-13T03:44:55.532116, 0.210155010223
2015-10-13T03:44:57.849418, 0.205804109573
2015-10-13T03:50:00.820898, 0.209445953369
2015-10-13T03:55:05.751707, 1.02589607239
2015-10-13T03:55:06.961255, 0.209120035172






RUN 2 - tornado (current state):
2015-10-15T11:24:08.214828, 1.12581682205
2015-10-15T11:25:53.674432, 0.632707834244
2015-10-15T11:25:56.090735, 1.41519904137
2015-10-15T11:29:46.859020, 1.52063202858
2015-10-15T11:30:59.647550, 1.2416639328
2015-10-15T11:31:02.118504, 1.46986603737
2015-10-15T11:36:06.597363, 0.655927181244
2015-10-15T11:36:09.191250, 0.587709903717
2015-10-15T11:41:13.476455, 1.30816602707
2015-10-15T11:41:15.914592, 1.43704295158
2015-10-15T11:44:13.417245, 0.530987977982
2015-10-15T11:46:19.533781, 1.37923598289
2015-10-15T11:46:22.032509, 1.49763298035
2015-10-15T11:51:25.875011, 0.629227876663
2015-10-15T11:51:29.457628, 2.5815050602
2015-10-15T11:56:33.632878, 1.38443589211
2015-10-15T11:56:36.120371, 1.4872879982
2015-10-15T11:58:28.763020, 0.499302864075
2015-10-15T12:01:40.488448, 0.533906936646
2015-10-15T12:01:42.942245, 1.45269989967
2015-10-15T12:05:37.120826, 0.644877195358
2015-10-15T12:06:46.672670, 1.19870209694
2015-10-15T12:06:49.118118, 1.44435405731
2015-10-15T12:11:06.953944, 0.400812149048
2015-10-15T12:11:53.376976, 1.14952111244
2015-10-15T12:11:55.832266, 1.45419502258
2015-10-15T12:16:59.596772, 0.986179113388
2015-10-15T12:17:02.072251, 1.47438502312
2015-10-15T12:22:07.528451, 2.5231730938
2015-10-15T12:22:09.984232, 1.45467400551
2015-10-15T12:25:34.387272, 0.287697076797
2015-10-15T12:27:13.522254, 1.48899483681
2015-10-15T12:27:15.984435, 1.46108293533
2015-10-15T12:30:36.399551, 0.248090028763
2015-10-15T12:32:20.438714, 1.50166797638
2015-10-15T12:32:23.119788, 0.674344062805
2015-10-15T12:35:38.689534, 0.221045017242
2015-10-15T12:37:27.506356, 1.15175008774
2015-10-15T12:37:29.981734, 1.47428584099
2015-10-15T12:41:04.705873, 0.20632982254
2015-10-15T12:42:28.005913, 0.770340204239
2015-10-15T12:42:34.589523, 0.540323972702
2015-10-15T12:42:37.027444, 1.43683004379
2015-10-15T12:47:41.397537, 1.38819885254
2015-10-15T12:47:43.893177, 1.49455189705


RUN 2 - flask (this PR .. same time period, next day):
2015-10-16T11:22:39.286675, 1.60724616051
2015-10-16T11:48:20.910908, 0.740996837616
2015-10-16T12:24:34.361291, 1.4495010376
2015-10-16T12:34:14.110175, 0.400887966156
2015-10-16T12:41:00.134272, 0.70098900795
2015-10-16T12:50:42.029543, 1.69085216522
```

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
utACK

@ouziel-slama ?

**Comment by ouziel-slama** [comment]
+1
ACK

**Comment by adamkrellenstein** [comment]
@robby-dermody, if you've tested this enough yourself, you can merge.

**Comment by robby-dermody** [comment]
Sounds good. I'll merge in sometime this week, after it runs a bit more.

**Pull request merged**
