### PR TITLE
[WIP] add config option to disable mempool syncing

### PR DESCRIPTION
**Pull request by rubensayshi**
this makes for a very light weight node to run (at least memory wise)! 

CLI PR: https://github.com/CounterpartyXCP/counterparty-cli/pull/76

### CODE REVIEW

**Comment by robby-dermody** [comment]
I think this will raise an Exception if `unconfirmed` is set to true with any API calls, see https://github.com/CounterpartyXCP/counterparty-lib/blob/develop/counterpartylib/lib/backend/addrindex.py#L203
https://github.com/CounterpartyXCP/counterparty-lib/blob/develop/counterpartylib/lib/backend/addrindex.py#L126

https://github.com/CounterpartyXCP/counterparty-lib/blob/7d97da448a75dba16232e757db28936ceec56839/counterpartylib/lib/transaction.py#L398

I think this is fine an expected though, as it's explicit (i.e. if a node is not getting unconfirmed tx, and you ask for an API call that takes into account unconfirmed tx, you should get an error back)

**Comment by robby-dermody** [comment]
@rubensayshi will test this more for unexpected side effects.

**Comment by rubensayshi** [comment]
@robby-dermody updated to make it functional, 

the problem is though that when you try to construct multiple transactions within 1 block it won't know that certain UTXOs are already spent so it will keep constructing with the same UTXO.  

not really sure how to get around this atm without tracking 0conf TXs :/

**Comment by robby-dermody** [comment]
Perhaps just some lightweight list that tracks utxos used for any transactions composed, and clears that out when a new block comes in and is processed? (You could maybe enhance the UTXO lock stuff we're doing to make it work in a mode that tracks until a block comes in and then expires it all... Or you could use make some other very simple way that will do this)... It's not perfect as it can't account for utxos used by other nodes, but may be good enough

**Comment by chiguireitor** [comment]
@rubensayshi is this PR ready or is there something left to do for it to work? I know it's ages since this PR was opened, but would like to know if you recall something about it

**Comment by chiguireitor** [comment]
Closing this, it has become incompatible with the indexd backend due to the elimination of the `searchrawtransactions` call

**Pull request closed without merging**
