### PR TITLE
Implemented micropayment channels for counterparty assets.

### PR DESCRIPTION
**Pull request by F483**
All commits needed have been squashed, see [micropayment_channels branch](https://github.com/F483/counterparty-lib/tree/micropayment_channels) for an unsquashed version and added micropayment code has 100% coverage. Note that this may contain some changes from @rubensayshi, if he has not already merged them.

Api documentation can [here](https://github.com/F483/counterparty-documentation/blob/master/Developers/API.md#mpc_make_deposit) and protocol documentation can be found [here](https://github.com/F483/counterparty-documentation/blob/master/Developers/micropayments.md), will create a PR for the documentation as soon as this PR is accepted.

New api calls start with mpc_ and micropayment code is in counterpartylib.lib.micropayments

Additionally I added an api call "sendrawtransaction" which pipes through to bitcoind, this helps a lot with mitigating race conditions in clients.

I also moved much of the signing/script code to its own python libray ([github](https://github.com/F483/micropayment-core), [pypi](https://pypi.python.org/pypi/micropayment_core)) so client that need it will not have to depend on counterpartylib and its extensive dependencies. This should belong to counterparty and I will gladly transfer ownership.

I will of course maintain this code and make any changes needed so this patches is accepted.

### CODE REVIEW

**Comment by F483** [comment]
I just added the test fixtures to the package, this lets me import and use the same test setup for my downstream [payment hub](https://github.com/F483/picopayments) and [payment hub client](https://github.com/F483/picopayments-client-python).

**Comment by rubensayshi** [comment]
Could you reopen the PR against `develop` ? :)

**Comment by rubensayshi** [comment]
actually we should probably merge https://github.com/CounterpartyXCP/counterparty-lib/pull/906 first and you rebase against that so the diff is limited to your changes.

**Comment by rubensayshi** [comment]
can you also open the documentation as a PR, because I'm starting with that and see some small things to comment on ;)

**Comment by F483** [comment]
Ah sorry I though I opened it against develop, will reopen against develop and also make a PR for the documentation.

**Comment by F483** [comment]
Reopened for develop branch https://github.com/CounterpartyXCP/counterparty-lib/pull/944

**Pull request closed without merging**
