### PR TITLE
Increase OP_RETURN to network defaults of 80 bytes

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by adamkrellenstein** [comment]
Do 80-byte `OP_RETURN` transactions get relayed and mined as fast as 40-byte ones?

This breaks the tests.

**Comment by btcdrak** [comment]
@adamkrellenstein One easy way to find out. Make two separate TXs (not linked in any way), one with a 40 byte OP return and the other with an 80 and see what happens.

**Comment by robby-dermody** [comment]
This is pending additional testing as to how rapidly these > 40 byte OP_RETURNS are mined on mainnet

**Comment by btcdrak** [comment]
I suggest, wait until CLTV gets to around 90% deployment, that will mean 90% of the hash power are running 0.11.2 which has the 80 byte policy.

You can check uptake here: https://data.bitcoinity.org/bitcoin/block_version/5y?c=block_version&r=week&t=a

**Comment by btcdrak** [comment]
OT: I am sorry I dont have time to fix tests etc. I was just bringing this to attention because I am concerned CP use the most efficient encoding rather than all these workarounds. I think it's probably not necessary to obfuscate outputs after this either, because the landscape has changed a lot and OP_RETURN is much more accepted for meta data.

**Comment by rubensayshi** [comment]
ping @robby-dermody @adamkrellenstein @btcdrak 

I think it would be safe to make the switch now.
Any idea on what kind of testing you guys want to see before making this change? (or not?)

I can update the tests to work with 80 bytes if that's all that is blocking this.

**Comment by btcdrak** [comment]
All pools have upgraded now so you absolutely should switch to OP_RETURN 80.

**Comment by robby-dermody** [comment]
@rubensayshi yes please create/update tests and we will merge

**Comment by robby-dermody** [comment]
closing, since #828 was merged in

**Pull request closed without merging**
