### PR TITLE
protocol changes to get full parse / reparse working again

### PR DESCRIPTION
**Pull request by pataegrillo**

### CODE REVIEW

**Comment by jdogresorg** [comment]
Doing a full parse on api1 using this PR. We can compare current database with this full parse version once the parse is completed in a few days.

**Comment by jotapea** [comment]
Hello, I've been trying to setup a federated node for v9.60 (and also for v9.59 from my repo fork) and "fednode tail counterparty" runs indefinitely in what seems to be looping in the parsing. I have two questions:

1. Why is looping the default behavior when it "fails"? This is making node operators waste computing resources / money.
2. How can I learn where the failure is? How are the fixes being determined? I'm interested in learning this debugging process...

**Comment by jotapea** [comment]
Hello, I've been trying to setup a federated node for v9.60 (and also for v9.59 from my repo fork) and "fednode tail counterparty" runs indefinitely in what seems to be looping in the parsing. I have two questions:

1. Why is looping the default behavior when it "fails"? This is making node operators waste computing resources / money.
2. How can I learn where the failure is? How are the fixes being determined? I'm interested in learning this debugging process...

**Comment by jdogresorg** [comment]
> 1. Why is looping the default behavior when it "fails"? 

In the past we had some cases where the CP API would occasionally crash or exit unexpectedly, leaving the node entirely dead until someone manually restarted CP. I believe we added a flag to docker to automatically restart the counterparty dockers if we detect they exited on anything but a normal shutdown.... You can change this behavior in the Docker file if you want... tho the only time this is a "problem" is when doing a parse/reparse and it consistently fails (not something normal people do).... IMO it is better to leave the auto-restart in than remove it.

2.How can I learn where the failure is? How are the fixes being determined? I'm interested in learning this debugging process...

The failure is where the CP code detects a sanity error due to incorrect balances.... the error is thrown in the CP console.

The fix is to compare the current ledger and the newly parsed ledger and compare credits/debits tables to detect any differences... when a difference is found, we track backwards to that difference and the TX that caused it, then look at the old tx and new tx and see what is different... then look back at the code for why it is parsing differently (in all cases so far, it has been protocol changes that were not added as protocol changes or protocol changes which had incorrect activation blocks.

Once we find the issue in the code that is causing the tx to parse in differently than the original ledger, we add a protocol change, then update the PR, then rollback the CP database to before the problem block/tx, then parse the transaction again and once again compare the databases to make sure that they match.

**Comment by jotapea** [comment]
IMO is better to surface the errors, to fix them. The choice of automatic restart is an advanced configuration that the node operators should decide, understanding the consequences (like possibility of missing errors / staying in a loop).

I believe this software needs to optimize to ONBOARD new nodes. This "continue looping" default behavior goes against this. I literally lost time and money because of this.

But thanks for letting me know.

**Comment by jdogresorg** [comment]
Pulling down PR changes to api1 and doing reparse on current mainnet/testnet databases to test

**Comment by jdogresorg** [comment]
jdog@eds-cp01:~$ fednode reparse counterparty-testnet
Starting federatednode_addrindexrs-testnet_1 ... done
Starting federatednode_bitcoin-testnet_1     ... done
[2022-11-12 06:34:47][INFO] Running v1.1.5 of counterparty-server.
[2022-11-12 06:34:47][INFO] Running v9.60.0 of counterparty-lib.
[2022-11-12 06:34:47][INFO] Acquiring lock.
[2022-11-12 06:34:47][INFO] Connecting to database (SQLite 3.24.0-r1).
[2022-11-12 06:35:12][INFO] Connecting to backend.
[2022-11-12 06:35:12][INFO] AddrIndexRs connecting...
[2022-11-12 06:35:12][INFO] Connected to AddrIndexRs!
[2022-11-12 06:35:12][INFO] Reparsing all transactions.
[2022-11-12 06:35:27][INFO] Testnet/regtest full reparse detected: Clearing all consensus hashes before performing reparse.
[2022-11-12 06:35:41][INFO] Block (re-parse): 310000 (hashes: L:1c223 / TX:1c223 / M:1c223)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310010 (hashes: L:e1ce9 / TX:e1ce9 / M:e1ce9)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310020 (hashes: L:8749e / TX:8749e / M:8749e)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310030 (hashes: L:4441e / TX:4441e / M:4441e)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310040 (hashes: L:246e6 / TX:246e6 / M:246e6)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310050 (hashes: L:79b8f / TX:79b8f / M:79b8f)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310060 (hashes: L:50ddc / TX:50ddc / M:50ddc)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310070 (hashes: L:c6cd3 / TX:c6cd3 / M:c6cd3)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310080 (hashes: L:69c18 / TX:69c18 / M:69c18)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310090 (hashes: L:ab36e / TX:ab36e / M:ab36e)
[2022-11-12 06:35:41][INFO] Block (re-parse): 310100 (hashes: L:c6441 / TX:c6441 / M:c6441)
...
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405800 (hashes: L:306b5 / TX:dedee / M:a070a)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405810 (hashes: L:3ac13 / TX:79448 / M:8d84f)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405820 (hashes: L:aad6f / TX:f141f / M:5879f)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405830 (hashes: L:cf453 / TX:30013 / M:d8ea0)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405840 (hashes: L:4c8fb / TX:dd62d / M:1b0d7)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405850 (hashes: L:d4c45 / TX:89bf2 / M:82ef4)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405860 (hashes: L:faf52 / TX:5ecee / M:a1c46)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405870 (hashes: L:202d4 / TX:fe88a / M:5acd8)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405880 (hashes: L:eed23 / TX:c3aab / M:361b8)
[2022-11-12 06:52:12][INFO] Block (re-parse): 2405890 (hashes: L:f0715 / TX:d2398 / M:030ce)
[2022-11-12 06:52:55][INFO] Database version number updated.
[2022-11-12 06:52:55][INFO] Reparse took 17.707 minutes.
[2022-11-12 06:52:55][INFO] Starting database VACUUM. This may take awhile...
[2022-11-12 06:53:52][INFO] Database VACUUM completed.

Testnet reparse looks good

**Comment by jdogresorg** [comment]
Starting full parse on mainnet

```
jdog@eds-cp01:~/federatednode$ fednode rollback 278270 counterparty
Starting federatednode_addrindexrs_1 ... done
Starting federatednode_bitcoin_1     ... done
[2022-11-15 06:37:21][INFO] Running v1.1.5 of counterparty-server.
[2022-11-15 06:37:21][INFO] Running v9.60.0 of counterparty-lib.
[2022-11-15 06:37:21][INFO] Acquiring lock.
[2022-11-15 06:37:21][INFO] Connecting to database (SQLite 3.24.0-r1).
[2022-11-15 06:39:11][INFO] Connecting to backend.
[2022-11-15 06:39:11][INFO] AddrIndexRs connecting...
[2022-11-15 06:39:11][INFO] Connected to AddrIndexRs!
[2022-11-15 06:39:11][INFO] Rolling back transactions to block 278270.
[2022-11-15 06:39:11][INFO] Could not roll back from undolog. Performing full reparse instead...
[2022-11-15 06:42:44][INFO] Block (re-parse): 278270 (hashes: L:7b0b7 / TX:7b0b7 / M:7b0b7)
[2022-11-15 06:44:22][INFO] Database version number updated.
[2022-11-15 06:44:22][INFO] Reparse took 5.180 minutes.

jdog@eds-cp01:~/federatednode$ fednode vacuum counterparty
Starting federatednode_bitcoin_1     ... done
Starting federatednode_addrindexrs_1 ... done
[2022-11-15 06:51:48][INFO] Running v1.1.5 of counterparty-server.
[2022-11-15 06:51:48][INFO] Running v9.60.0 of counterparty-lib.
[2022-11-15 06:51:48][INFO] Acquiring lock.
[2022-11-15 06:51:48][INFO] Connecting to database (SQLite 3.24.0-r1).
[2022-11-15 06:51:48][INFO] Starting database VACUUM. This may take awhile...
[2022-11-15 06:51:48][INFO] Database VACUUM completed.

jdog@eds-cp01:~/federatednode$ fednode start counterparty
Starting counterparty ... done
jdog@eds-cp01:~/federatednode$ fednode tail counterparty
Attaching to federatednode_counterparty_1
counterparty_1           | [2022-11-15 06:52:01][INFO] Running v1.1.5 of counterparty-server.
counterparty_1           | [2022-11-15 06:52:01][INFO] Running v9.60.0 of counterparty-lib.
counterparty_1           | [2022-11-15 06:52:01][INFO] Acquiring lock.
counterparty_1           | [2022-11-15 06:52:01][INFO] Connecting to database (SQLite 3.24.0-r1).
counterparty_1           | [2022-11-15 06:52:01][INFO] Connecting to backend.
counterparty_1           | [2022-11-15 06:52:01][INFO] AddrIndexRs connecting...
counterparty_1           | [2022-11-15 06:52:01][INFO] Connected to AddrIndexRs!
counterparty_1           | [2022-11-15 06:52:01][INFO] Starting API Server.
counterparty_1           | [2022-11-15 06:52:02][INFO] Resuming parsing.
counterparty_1           | [2022-11-15 06:52:02][INFO] Block: 278271 (0.50s, hashes: L:f705f / TX:f705f / M:f705f)
counterparty_1           | [2022-11-15 06:52:02][INFO] Block: 278272 (0.19s, hashes: L:03a20 / TX:03a20 / M:03a20)
counterparty_1           | [2022-11-15 06:52:03][INFO] Block: 278273 (0.39s, hashes: L:6f1bd / TX:6f1bd / M:6f1bd)
counterparty_1           | [2022-11-15 06:52:03][INFO] Block: 278274 (0.14s, hashes: L:cd646 / TX:cd646 / M:cd646)
counterparty_1           | [2022-11-15 06:52:03][INFO] Block: 278275 (0.16s, hashes: L:c4319 / TX:c4319 / M:c4319)
counterparty_1           | [2022-11-15 06:52:03][INFO] Block: 278276 (0.27s, hashes: L:72171 / TX:72171 / M:72171)
counterparty_1           | [2022-11-15 06:52:04][INFO] Block: 278277 (0.43s, hashes: L:b4e12 / TX:b4e12 / M:b4e12)
counterparty_1           | [2022-11-15 06:52:04][INFO] Block: 278278 (0.23s, hashes: L:e2ab8 / TX:e2ab8 / M:e2ab8)
counterparty_1           | [2022-11-15 06:52:04][INFO] Block: 278279 (0.16s, hashes: L:dc9a7 / TX:dc9a7 / M:dc9a7)
counterparty_1           | [2022-11-15 06:52:05][INFO] Block: 278280 (0.43s, hashes: L:95a76 / TX:95a76 / M:95a76)
counterparty_1           | [2022-11-15 06:52:05][INFO] Block: 278281 (0.09s, hashes: L:5a541 / TX:5a541 / M:5a541)
...
```

**Comment by jdogresorg** [comment]
full parse completed

```
jdog@eds-cp01:~/federatednode$ fednode start counterparty
Starting counterparty ... done
jdog@eds-cp01:~/federatednode$ fednode tail counterparty
Attaching to federatednode_counterparty_1
counterparty_1           | [2022-11-15 06:52:01][INFO] Running v1.1.5 of counterparty-server.
counterparty_1           | [2022-11-15 06:52:01][INFO] Running v9.60.0 of counterparty-lib.
counterparty_1           | [2022-11-15 06:52:01][INFO] Acquiring lock.
counterparty_1           | [2022-11-15 06:52:01][INFO] Connecting to database (SQLite 3.24.0-r1).
counterparty_1           | [2022-11-15 06:52:01][INFO] Connecting to backend.
counterparty_1           | [2022-11-15 06:52:01][INFO] AddrIndexRs connecting...
counterparty_1           | [2022-11-15 06:52:01][INFO] Connected to AddrIndexRs!
counterparty_1           | [2022-11-15 06:52:01][INFO] Starting API Server.
counterparty_1           | [2022-11-15 06:52:02][INFO] Resuming parsing.
counterparty_1           | [2022-11-15 06:52:02][INFO] Block: 278271 (0.50s, hashes: L:f705f / TX:f705f / M:f705f)
counterparty_1           | [2022-11-15 06:52:02][INFO] Block: 278272 (0.19s, hashes: L:03a20 / TX:03a20 / M:03a20)
counterparty_1           | [2022-11-15 06:52:03][INFO] Block: 278273 (0.39s, hashes: L:6f1bd / TX:6f1bd / M:6f1bd)
counterparty_1           | [2022-11-15 06:52:03][INFO] Block: 278274 (0.14s, hashes: L:cd646 / TX:cd646 / M:cd646)
counterparty_1           | [2022-11-15 06:52:03][INFO] Block: 278275 (0.16s, hashes: L:c4319 / TX:c4319 / M:c4319)
counterparty_1           | [2022-11-15 06:52:03][INFO] Block: 278276 (0.27s, hashes: L:72171 / TX:72171 / M:72171)
counterparty_1           | [2022-11-15 06:52:04][INFO] Block: 278277 (0.43s, hashes: L:b4e12 / TX:b4e12 / M:b4e12)
counterparty_1           | [2022-11-15 06:52:04][INFO] Block: 278278 (0.23s, hashes: L:e2ab8 / TX:e2ab8 / M:e2ab8)
counterparty_1           | [2022-11-15 06:52:04][INFO] Block: 278279 (0.16s, hashes: L:dc9a7 / TX:dc9a7 / M:dc9a7)
counterparty_1           | [2022-11-15 06:52:05][INFO] Block: 278280 (0.43s, hashes: L:95a76 / TX:95a76 / M:95a76)
counterparty_1           | [2022-11-15 06:52:05][INFO] Block: 278281 (0.09s, hashes: L:5a541 / TX:5a541 / M:5a541)
...
counterparty_1           | [2022-11-27 18:51:40][INFO] Block: 764941 (12.88s, hashes: L:c6ab0 / TX:2a29f / M:e35ae)
counterparty_1           | [2022-11-27 18:55:10][INFO] Dispense: 1 PEPEUNITY from 19kKpxnzcCKivtApiXbgzVwbNnZFVDvz6q to 193J7RVEY2BgA5aKfL6BBAVSyiS1UyBRG6 (463393e30a730261d209dd683fd13c575e03ddf2bd7d136d083dd17b5fb0952d)
counterparty_1           | [2022-11-27 18:55:10][INFO] Send: 1 BCYDRAGON from 1STACKukgv78evq6PrqxAChbW6BKKCopX to 1KRN8QwfccKX6dUzBVwgTw73FMdN1NFnnH (2b9719b065816ed1e83e4ed488574aa67c67054c0d90cc6c554cc1ce8b5cb281) [valid]
counterparty_1           | [2022-11-27 18:55:10][INFO] Dispenser: 1Faj1huoNSDZaUwZGJN6jaRqTHpkJTSNPL closed dispenser for XCP (dispenser empty)
counterparty_1           | [2022-11-27 18:55:10][INFO] Dispense: 527.0 XCP from 1Faj1huoNSDZaUwZGJN6jaRqTHpkJTSNPL to 1KGf5Tcryp34J2TkSYWaqRjyCLcj5aSPYK (dcb9bd23688543a02049b0aae24c888bd760a9666465db5081b17941f3c026cf)
counterparty_1           | [2022-11-27 18:55:19][INFO] Block: 764942 (10.95s, hashes: L:1e87a / TX:3ef83 / M:74cae)
counterparty_1           | [2022-11-27 19:10:02][INFO] Issuance: 1JJP986hdU9Qy9b49rafM9FoXdbz1Mgbjo created 17 of indivisible asset SPACEBOY (582ee7080334b957fd67e1541313a7a7745d419be2fbff800d8f5af0bd53cf5c) [valid]
counterparty_1           | [2022-11-27 19:10:02][INFO] Dispenser: 1BkR7sfGxwwqhNWiT9LMGErs7du7e9AhXQ opened a dispenser for asset XCP with 886.00000000 balance, giving 1.00000000 XCP for each 0.00021900 BTC
counterparty_1           | [2022-11-27 19:10:02][INFO] Dispenser: 1JsPoV5USoFM7441KtGXtvMH5ezNwq9Uak closed dispenser for XCP (dispenser empty)
counterparty_1           | [2022-11-27 19:10:02][INFO] Dispense: 531.0 XCP from 1JsPoV5USoFM7441KtGXtvMH5ezNwq9Uak to 1KGf5Tcryp34J2TkSYWaqRjyCLcj5aSPYK (afbd95a785f0ed3a4c9932df067b04509ab2d9d2ba08585ca517e9a0e3a3f2db)
counterparty_1           | [2022-11-27 19:10:02][INFO] Dispense: 460.0 XCP from 1NGKt6HGFj2bCf4Z2wQ7v2Zu5kTiTRuccA to 1KGf5Tcryp34J2TkSYWaqRjyCLcj5aSPYK (e36d854ec853f1535d802b08cf278899aba82a9728372b107cef7774434e1702)
counterparty_1           | [2022-11-27 19:10:11][INFO] Block: 764943 (13.36s, hashes: L:f3fc7 / TX:ee6a9 / M:436c7)
```

**Comment by jotapea** [comment]
@jdogresorg Is there a configuration to help speed up the parsing? My v9.60 node is still syncing, and it started before the sync documented here...

**Comment by jdogresorg** [comment]
@jotapea All the parsing/reparsing changes are listed here in this PR... the speed optimization your asking about is he indexes on the dispensers table.

You can pull down the changes here in this PR, rollback the CP database to the first block, then do a full parse (expect it to take a week+ still).... I would wait until 9.60.1 before trying a full sync or reparse, as these changes will be fully tested/verified in the next release.... right now still testing these fixes/changes.

**Comment by jotapea** [comment]
Ok thank you for explaining. My sync is at block 761730, so at this point I will just wait for it to complete.

**Comment by jdogresorg** [comment]
Reparse of full-parse database completed without any issues or ledger conflicts.
```
jdog@eds-cp01:~$ fednode reparse counterparty
Starting federatednode_bitcoin_1     ... done
Starting federatednode_addrindexrs_1 ... done
[2022-11-27 20:00:35][INFO] Running v1.1.5 of counterparty-server.
[2022-11-27 20:00:35][INFO] Running v9.60.0 of counterparty-lib.
[2022-11-27 20:00:35][INFO] Acquiring lock.
[2022-11-27 20:00:35][INFO] Connecting to database (SQLite 3.24.0-r1).
[2022-11-27 20:02:06][INFO] Connecting to backend.
[2022-11-27 20:02:06][INFO] AddrIndexRs connecting...
[2022-11-27 20:02:06][INFO] Connected to AddrIndexRs!
[2022-11-27 20:02:06][INFO] Reparsing all transactions.
[2022-11-27 20:02:23][INFO] Block (re-parse): 278270 (hashes: L:7b0b7 / TX:7b0b7 / M:7b0b7)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278280 (hashes: L:95a76 / TX:95a76 / M:95a76)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278290 (hashes: L:e7ad8 / TX:e7ad8 / M:e7ad8)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278300 (hashes: L:bbc05 / TX:bbc05 / M:bbc05)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278310 (hashes: L:8b264 / TX:8b264 / M:8b264)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278320 (hashes: L:b139f / TX:821db / M:f5887)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278330 (hashes: L:cf0ef / TX:babb6 / M:1dc19)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278340 (hashes: L:d17d3 / TX:fcb5d / M:61010)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278350 (hashes: L:599b8 / TX:86f69 / M:3fd81)
[2022-11-27 20:02:23][INFO] Block (re-parse): 278360 (hashes: L:011a3 / TX:5dd5c / M:72760)
...
[2022-11-28 18:25:24][INFO] Block (re-parse): 764850 (hashes: L:aa9cc / TX:de4ad / M:cd2e9)
[2022-11-28 18:25:30][INFO] Block (re-parse): 764860 (hashes: L:f0bd8 / TX:897d0 / M:b1ede)
[2022-11-28 18:25:35][INFO] Block (re-parse): 764870 (hashes: L:0d1bf / TX:f8126 / M:0f32e)
[2022-11-28 18:25:41][INFO] Block (re-parse): 764880 (hashes: L:5df53 / TX:654a6 / M:8fcea)
[2022-11-28 18:25:47][INFO] Block (re-parse): 764890 (hashes: L:9dccd / TX:00a3e / M:a8549)
[2022-11-28 18:25:53][INFO] Block (re-parse): 764900 (hashes: L:54256 / TX:00e3f / M:f3b1b)
[2022-11-28 18:25:59][INFO] Block (re-parse): 764910 (hashes: L:804a5 / TX:20c38 / M:78fe9)
[2022-11-28 18:26:04][INFO] Block (re-parse): 764920 (hashes: L:52d9c / TX:2af10 / M:55b56)
[2022-11-28 18:26:10][INFO] Block (re-parse): 764930 (hashes: L:eae19 / TX:62bf8 / M:0a7eb)
[2022-11-28 18:26:17][INFO] Block (re-parse): 764940 (hashes: L:77bbb / TX:c77ee / M:0619a)
[2022-11-28 18:28:57][INFO] Database version number updated.
[2022-11-28 18:28:57][INFO] Reparse took 1255.671 minutes.
[2022-11-28 18:28:57][INFO] Starting database VACUUM. This may take awhile...
[2022-11-28 18:46:38][INFO] Database VACUUM completed.
```

Now need to do final comparisons between fullparse/reparsed database and the bootstrap database to ensure that the ledgers match.

**Comment by pataegrillo** [comment]
To explain a little, whenever we did a full parse, we took the "good" database, which is the one used by everyone and it can be seen in xchain, and compared with the database result from the recent parsing. We did this several times because there was always a difference caused by a missing protocol changes in the parse. For example, before, whenever an order with a btcpay had many matches and enough to fill the order, if the last match got paid the order was marked "filled", and later if any of the other matches expired, the order remained "filled" and was not opened again. We fixed this, but we didn't add a protocol change, so, the full parse left many orders "open" and differents matches were created.

We created two tools for this. One to rollback to any block, without using UNDOLOG, basically it cuts any table from a specific block_index and recalculate balances, order status, order remainings, dispensers status and dispensers remainings, really helpful to debug any parsing problem. And the other to compare data from two databases, specifically the tables credits, debits and order_matches.

The comparison is simple, we check every row from the credits and debits table to be equal. If there is a single difference, then the full parse is wrong. Not only that, a single difference would generate a cascade of differences and errors that normally crash counterparty parsing.

Today (28/11/2022), after several protocol_changes, we did a comparison between the "good" database and the last full parse we did. It checked 3022343 credits and 2108534 debits and the results were good, the databases are equal and they don't have a single difference. So, I think we are ready to merged the pull request and enable the full parsing again.

**Review by jdogresorg — APPROVED** [review]

**Comment by jdogresorg** [comment]
Anyone who wants to update their counterparty fednode with this update can so by running the following commands:

```
fednode update counterparty counterparty-testnet
fednode stop counterparty counterparty-testnet
sudo su
rm -f federatednode/data/counterparty/counterparty.db*
exit
fednode rebuild counterparty counterparty-testnet
```

We will be wrapping up this and some additional optimizations into the 9.60.1 release in a few days.

**Comment by jotapea** [comment]
@pataegrillo I really appreciate your explanation. And your work.

**Comment by jotapea** [comment]
@jdogresorg My previously referenced v9.60 node is still syncing (<1000 blocks to go), but I also started a new node from scratch.

This second one was installed as `base`. And both bitcoin and addrindexrs are synced.

But now `fednode start counterparty` shows the following error:

```
counterparty_1          | [2022-12-08 23:16:44][INFO] Running v1.1.5 of counterparty-server.
counterparty_1          | [2022-12-08 23:16:44][INFO] Running v9.60.0 of counterparty-lib.
counterparty_1          | [2022-12-08 23:16:44][INFO] Acquiring lock.
counterparty_1          | [2022-12-08 23:16:44][INFO] Connecting to database (SQLite 3.24.0-r1).
counterparty_1          | [2022-12-08 23:16:44][ERROR] Unhandled Exception
counterparty_1          | Traceback (most recent call last):
counterparty_1          |   File "/usr/local/bin/counterparty-server", line 11, in <module>
counterparty_1          |     load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
counterparty_1          |   File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
counterparty_1          |     server.main()
counterparty_1          |   File "/counterparty-cli/counterpartycli/server.py", line 156, in main
counterparty_1          |     db = init_with_catch(server.initialise, init_args)
counterparty_1          |   File "/counterparty-cli/counterpartycli/server.py", line 118, in init_with_catch
counterparty_1          |     return fn(**init_args)
counterparty_1          |   File "/counterparty-lib/counterpartylib/server.py", line 83, in initialise
counterparty_1          |     return initialise_db()
counterparty_1          |   File "/counterparty-lib/counterpartylib/server.py", line 467, in initialise_db
counterparty_1          |     util.CURRENT_BLOCK_INDEX = blocks.last_db_index(db)
counterparty_1          |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1280, in last_db_index
counterparty_1          |     blocks = list(cursor.execute('''SELECT * FROM blocks WHERE block_index = (SELECT MAX(block_index) from blocks)'''))
counterparty_1          |   File "src/cursor.c", line 1019, in APSWCursor_execute.sqlite3_prepare
counterparty_1          |   File "src/statementcache.c", line 386, in sqlite3_prepare
counterparty_1          | apsw.CorruptError: CorruptError: database disk image is malformed
```

And if I try the commands from https://github.com/CounterpartyXCP/counterparty-lib/pull/1212#issuecomment-1329928362, the step

> rm -f federatednode/data/counterparty/counterparty.db*

is not working as I don't have anything under federatednode/data/*. Skipping this step results in the same error.

**Comment by jdogresorg** [comment]
the `database disk image is malformed` typically happens when the bootstrap images overwrite one another. Until recently there has been an issue with the bootstrap downloading process where the mainnet and testnet instances download BOTH the mainnet and testnet bootstraps, at the same time, quite often ovewriting one another, and sometimes resulting in the `database disk image is malformed` error.

I have had Javier fix this issue in this PR https://github.com/CounterpartyXCP/counterparty-lib/pull/1218 so that now when you start up counterparty mainnet, only the mainnet bootstrap is downloaded... if you start up counterparty testnet, only the testnet bootstrap is downloaded.

it is strange that you dont have any federatednode/data/counterparty directory, as the fednode install process sets up a symlink from `/var/lib/docker/volumes/federatednode_counterparty-data/_data` to `federatednode/data/counterparty` so that the data in the docker volume is easily accessible at a convenient local folder in the fednode/data directory.

I suggest you 
1. Stop your fednode `fednode stop counterparty counterparty-testnet`
2. Manually remove the `counterparty.db` and `counterparty.testnet.db` files, wherever they are located on your system
3. Start up counterparty and let it download the bootstrap and start up completely `fednode start counterparty;fednode tail counterparty`
4. Start up counterparty-testnet and let it start up completely `fednode start counterparty-testnet; fednode tail counterparty-testnet`

Alternatively, you should now be able to use the `--no-bootstrap` on a fednode install :
1. First delete your `counterparty.db` and `counterparty.testnet.db` files, wherever they are in your system
2. Run the following commands to update your fednode :
```
cd federatednode/
git pull
fednode update
fednode rebuild counterparty counterparty-testnet --no-cache
fednode uninstall
fednode install base master --no-bootstrap
```

**Comment by jotapea** [comment]
@jdogresorg The sync is working for me now, done with the `--no-bootstrap` and also considering this https://github.com/CounterpartyXCP/federatednode/issues/343.

Very cool to see the parsing taking less than a second for most blocks @pataegrillo !

**Pull request merged**
