### PR TITLE
[WIP] upgrade APSW/SQLite to 3.12.2 and enlarge page_cache

### PR DESCRIPTION
**Pull request by rubensayshi**
Fixes: https://github.com/CounterpartyXCP/counterparty-lib/issues/871

Will update APSW / SQLite, testing it now...

### CODE REVIEW

**Comment by rubensayshi** [comment]
Relevant changes in SQLite changelog since 3.8.7 from http://www.sqlite.org/changes.html:

#### 2016-03-29 (3.12.0)
The SQLITE_DEFAULT_PAGE_SIZE is increased from 1024 to 4096. The SQLITE_DEFAULT_CACHE_SIZE is changed from 2000 to -2000 so the same amount of cache memory is used by default. See the application note on the version 3.12.0 page size change for further information.

**Comment by rubensayshi** [comment]
tests fail cuz the fixtures .sql files contain "PRAGMA page_size=1024;" and after upgrade will contain "PRAGMA page_size=4096;".  

so if we're gonna upgrade this we need devs to upgrade to make their tests pass ;)

**Comment by rubensayshi** [comment]
added command line tool to do the upgrade:
 - `python ./tools/upgradesqlitepagesize.py ~/.local/share/counterparty/counterparty.testnet.db`
 - `python ./tools/upgradesqlitepagesize.py ~/.local/share/counterparty/counterparty.db`

untested on mac/windows

**Comment by rubensayshi** [comment]
Another breaking change; can't do `backup` on a DB that's already been written to, but the first `initialise_db` that was being done before the `backup` was useless anyway, so removed it.

**Comment by unsystemizer** [comment]
@robby-dermody on my Ubuntu 16 `apt-get upgrade` overwrote the manually installed Sqlite 3.12.2 with 3.13.x. I don't know if this could impact anything in Docker or otherwise - if yes maybe we should "hold" sqlite3 to prevent it from being upgraded?

**Comment by robby-dermody** [comment]
@unsystemizer yes, the docker setup will avoid those kinds of situations

**Comment by robby-dermody** [comment]
@rubensayshi if we merge this, notes on how to upgrade will need to be written in `Changelog.md` (or somewhere else and linked to `Changelog.md`)

on that topic, probably a good practice for us to commit additions to `Changelog.md` as part of the actual PR, instead of all at once in preparation for a release. Thoughts?

**Comment by rubensayshi** [comment]
yea, I'll try making a habbit of adding thing to `Changelog.md`.

not sure how we can make it extra clear though that they should be doing something, like upgrading sqlite

**Comment by unsystemizer** [comment]
With Ubuntu 16.04 (which we don't yet "officially" support although it works) they would need to downgrade. 
counterparty-lib's readme.md could contain a note on that (although we can leave Ubuntu 14.04 as the primary/default distro and version we support).

**Comment by rubensayshi** [comment]
@unsystemizer what do you mean downgrade?

**Comment by unsystemizer** [comment]
I installed apsw/Sqlite 3.12.2 on my system (as I was testing it for a while). Earlier this week I executed `apt-get upgrade` and I saw Sqlite v3.1.13 was installed over it. 
As I mentioned in https://github.com/CounterpartyXCP/counterparty-lib/issues/871, Ubuntu 16.04 shipped with v3.11 so it was all good as far as my upgrade was concerned until they released v3.13.

Now, I didn't notice any issues, but at least in theory apsw 3.12.2 should be paired with a different version of Sqlite3 and apsw 3.12.2 is the latest release, so obviously not holding sqlite3 from automatic OS updates creates a bad situation. It's not a problem on Ubuntu 14.04 because you won't see a newer version, but on Ubuntu 16.04 it's different, that's why I asked.

**Comment by rubensayshi** [comment]
afaik when apsw is build (`python setup.py install_apsw`) it downloads the corresponding sqlite version to compile with.  
because the apsw versions correspond with the sqlite versions and can't build against a different one.

**Comment by unsystemizer** [comment]
Yes, that's why a Fed Node-like script should "hold" sqlite3 at the pre-set version (3.12.2, at the moment). 
pip3 can't control OS-level stuff, but Fed Node script can. Regarding the former, I wonder what happens with pip, counterparty-lib and apsw if someone tries to install counterparty-lib on the latest Ubuntu 16.04 where sqlite3 is v3.13..

**Comment by rubensayshi** [comment]
when apsw install it downloads a 'local' copy of the sqlite version it needs, it's not using the globally installed sqlite

**Comment by robby-dermody** [comment]
@rubensayshi if you think this is ready feel free merge it. I suspect the fednode counterparty-server container on develop may need an tweak to have that specific version, and the bootstrap DB will remain at the 1024 kb page size etc until the next release of course. I can do any necessary fednode updates when I get back.

**Comment by unsystemizer** [comment]
@robby-dermody check out https://github.com/CounterpartyXCP/counterparty-lib/issues/950, I think I hit the 2GB limit which (I'm still troubleshooting) could be the limit of pages with 1kb block size.

**Comment by unsystemizer** [comment]
The maximum Sqlite3 DB size using 1KB pages is 2 TB (earlier today I mistakenly calculated 2 GB), so there's no danger of hitting that limit soon, it seems.

**Comment by chiguireitor** [comment]
Closing this as it is being manually merged to solve conflicts.

**Pull request closed without merging**
