### PR TITLE
Add the endpoint for the healthcheck.

### PR DESCRIPTION
**Pull request by cryptcoin-junkey**
This will be useful if you want to run the clusters behind your load balancer.

### CODE REVIEW

**Comment by chiguireitor** [comment]
This seems interesting, any particular reason for naming the endpoint "healthz" with a z at the end?

**Comment by droplister** [comment]
Does the load balancer prevent you from using /_api/ because you can't be sure which node you're on?

```
  "counterparty-server_caught_up": true,
  "counterparty": "OK"
```

**Comment by chiguireitor** [comment]
I guess this call is meant to have http semantics bolted on, to help in scenarios like i.e. a kubernetes load balancer for elastic growing of a cluster.

**Comment by chiguireitor** [comment]
Please @cryptcoin-junkey update your test scenarios so travis passes (circleci is failing because the current plan can't cover the required testing container).

Here's a handy script someone passed down to me to update them:

```bash
#!/bin/bash
py.test --capture=no --skiptestbook=all --scenario=unittest_fixture --savescenarios counterpartylib/test/integration_test.py
py.test --capture=no --skiptestbook=all --scenario=simplesig --savescenarios counterpartylib/test/integration_test.py
py.test --capture=no --skiptestbook=all --scenario=multisig_1_of_2 --savescenarios counterpartylib/test/integration_test.py
py.test --capture=no --skiptestbook=all --scenario=multisig_2_of_2 --savescenarios counterpartylib/test/integration_test.py
py.test --capture=no --skiptestbook=all --scenario=multisig_1_of_3 --savescenarios counterpartylib/test/integration_test.py
py.test --capture=no --skiptestbook=all --scenario=multisig_2_of_3 --savescenarios counterpartylib/test/integration_test.py
py.test --capture=no --skiptestbook=all --scenario=multisig_3_of_3 --savescenarios counterpartylib/test/integration_test.py
py.test --capture=no --skiptestbook=all --scenario=parseblock_unittest_fixture --savescenarios counterpartylib/test/integration_test.py

mv counterpartylib/test/fixtures/scenarios/unittest_fixture.new.json counterpartylib/test/fixtures/scenarios/unittest_fixture.json; mv counterpartylib/test/fixtures/scenarios/unittest_fixture.new.sql counterpartylib/test/fixtures/scenarios/unittest_fixture.sql; mv counterpartylib/test/fixtures/scenarios/unittest_fixture.new.log counterpartylib/test/fixtures/scenarios/unittest_fixture.log
mv counterpartylib/test/fixtures/scenarios/simplesig.new.json counterpartylib/test/fixtures/scenarios/simplesig.json; mv counterpartylib/test/fixtures/scenarios/simplesig.new.sql counterpartylib/test/fixtures/scenarios/simplesig.sql; mv counterpartylib/test/fixtures/scenarios/simplesig.new.log counterpartylib/test/fixtures/scenarios/simplesig.log
mv counterpartylib/test/fixtures/scenarios/multisig_1_of_2.new.json counterpartylib/test/fixtures/scenarios/multisig_1_of_2.json; mv counterpartylib/test/fixtures/scenarios/multisig_1_of_2.new.sql counterpartylib/test/fixtures/scenarios/multisig_1_of_2.sql; mv counterpartylib/test/fixtures/scenarios/multisig_1_of_2.new.log counterpartylib/test/fixtures/scenarios/multisig_1_of_2.log
mv counterpartylib/test/fixtures/scenarios/multisig_2_of_2.new.json counterpartylib/test/fixtures/scenarios/multisig_2_of_2.json; mv counterpartylib/test/fixtures/scenarios/multisig_2_of_2.new.sql counterpartylib/test/fixtures/scenarios/multisig_2_of_2.sql; mv counterpartylib/test/fixtures/scenarios/multisig_2_of_2.new.log counterpartylib/test/fixtures/scenarios/multisig_2_of_2.log
mv counterpartylib/test/fixtures/scenarios/multisig_1_of_3.new.json counterpartylib/test/fixtures/scenarios/multisig_1_of_3.json; mv counterpartylib/test/fixtures/scenarios/multisig_1_of_3.new.sql counterpartylib/test/fixtures/scenarios/multisig_1_of_3.sql; mv counterpartylib/test/fixtures/scenarios/multisig_1_of_3.new.log counterpartylib/test/fixtures/scenarios/multisig_1_of_3.log
mv counterpartylib/test/fixtures/scenarios/multisig_2_of_3.new.json counterpartylib/test/fixtures/scenarios/multisig_2_of_3.json; mv counterpartylib/test/fixtures/scenarios/multisig_2_of_3.new.sql counterpartylib/test/fixtures/scenarios/multisig_2_of_3.sql; mv counterpartylib/test/fixtures/scenarios/multisig_2_of_3.new.log counterpartylib/test/fixtures/scenarios/multisig_2_of_3.log
mv counterpartylib/test/fixtures/scenarios/multisig_3_of_3.new.json counterpartylib/test/fixtures/scenarios/multisig_3_of_3.json; mv counterpartylib/test/fixtures/scenarios/multisig_3_of_3.new.sql counterpartylib/test/fixtures/scenarios/multisig_3_of_3.sql; mv counterpartylib/test/fixtures/scenarios/multisig_3_of_3.new.log counterpartylib/test/fixtures/scenarios/multisig_3_of_3.log
mv counterpartylib/test/fixtures/scenarios/parseblock_unittest_fixture.new.json counterpartylib/test/fixtures/scenarios/parseblock_unittest_fixture.json; mv counterpartylib/test/fixtures/scenarios/parseblock_unittest_fixture.new.sql counterpartylib/test/fixtures/scenarios/parseblock_unittest_fixture.sql; mv counterpartylib/test/fixtures/scenarios/parseblock_unittest_fixture.new.log counterpartylib/test/fixtures/scenarios/parseblock_unittest_fixture.log
```

**Comment by chiguireitor** [comment]
Merged manually on another commit

**Pull request closed without merging**
