### PR TITLE
Partial Crash Prevention

### PR DESCRIPTION
**Pull request by adamkrellenstein**

### CODE REVIEW

**Comment by ouziel-slama** [comment]
ACK

**Comment by robby-dermody** [comment]
@adamkrellenstein Can we skip just the transaction itself instead of skipping all transactions in the block? That would be much preferable.

**Comment by adamkrellenstein** [comment]
we can't because of this line: https://github.com/CounterpartyXCP/counterparty-lib/pull/838/files#diff-a7b98d56d05b9a595e317923cab93688L1125

**Comment by robby-dermody** [comment]
closing in favor of #862

**Pull request closed without merging**
