### PR TITLE
9.61.0 Release

### PR DESCRIPTION
**Pull request by jdogresorg**
# 9.61.0 Release Notes
- Bumped bitcoin core version to 25.1  ([view](https://github.com/CounterpartyXCP/federatednode/pull/355))
- Adjusted DEFAULT_MULTISIG_DUST_SIZE (7800->1000) ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1244))
- Fixed issue with oracle function returning bad values ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1252))
- Fixed issue with change smaller than DUST throwing error  ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1228))
- Fixed issue with issuances and callability error ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1219))
- Fixed issue with issuance backwards compatability ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1258))
- Fixed issue with dividends not working on reset assets ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1257))
- Redefined EMPTY address to mean no XCP or BTC history ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1255))
- Fixed issue with skipping owner validation on numeric issuances ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1260))
- Fixed issue with sweeps not transferring asset ownership if no supply issued ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1259))
- Added `origin` field to dispensers (allows refill/close/reopen from `origin`) ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1253))
- Added support for triggering dispenses on all tx outputs ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1222))
- Fixed issue with Asset description deleted when null ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1262))
- Added max dispense limit of 1000 ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1264))
- Fixed issue with being unable to lock and change asset description ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1265))
- Added DISPENSER_CLOSE_DELAY to delay closing dispensers 5 blocks ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1266))
- Added MAX_REFILLS limit of 5 ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1267))
- Added dynamic XCP fee on sweeps ([view](https://github.com/CounterpartyXCP/counterparty-lib/pull/1274))

## Upgrade Notes
```
fednode stop
cd federatednode/
git pull
fednode update
fednode rebuild bitcoin bitcoin-testnet --no-cache
fednode rebuild addrindexrs addrindexrs-testnet --no-cache
fednode stop
sudo rm -f data/addrindexrs/*
sudo rm -f data/counterparty/*
fednode start
```

### CODE REVIEW

**Comment by jdogresorg** [comment]
## Bootstrap reparse
```
[2023-11-16 00:30:49][INFO] Running v1.1.5 of counterparty-server.
[2023-11-16 00:30:49][INFO] Running v9.61.0 of counterparty-lib.
[2023-11-16 00:30:49][INFO] Acquiring lock.
[2023-11-16 00:30:49][INFO] Connecting to database (SQLite 3.24.0-r1).
[2023-11-16 00:30:49][INFO] Connecting to backend.
[2023-11-16 00:30:49][INFO] AddrIndexRs connecting...
[2023-11-16 00:30:49][INFO] Connected to AddrIndexRs!
[2023-11-16 00:30:49][INFO] Reparsing all transactions.
...
[2023-11-17 00:26:52][INFO] Block (re-parse): 815850 (hashes: L:35619 / TX:bcff0 / M:3c036 [overwrote 5c1a4491c8a5f937acd2cf3a1565397a787dbe1a7bbc20ad00eb12c75720e49b])
[2023-11-17 00:26:59][INFO] Block (re-parse): 815860 (hashes: L:0ea27 / TX:770d0 / M:f6e0f [overwrote c0cc1ec6d535d21c01b965d2a1f397e8158dd85630d13b08a80e8e944844eb01])
[2023-11-17 00:27:04][WARNING] Not storing [dispenser] tx [7d5afa2024184f714045cea245ae8f7f5294740bf45138f1ac4a6c7c1c56a0ab]: invalid: address doesnt has an open dispenser for asset CAPSULEPEPE
[2023-11-17 00:27:05][INFO] Block (re-parse): 815870 (hashes: L:4e070 / TX:395fa / M:7256c [overwrote cff0215e7173be405b4f7b2f69e94d0425dd27d9f035e5883ed8c881c7e79b8d])
[2023-11-17 00:27:12][INFO] Block (re-parse): 815880 (hashes: L:c2d5e / TX:523a1 / M:b9496 [overwrote 6fc2b880bb4bd929b92a56ae9b3c05d95f9072a34cc43a2f455d371462d1ae5f])
[2023-11-17 00:27:19][WARNING] Not storing [dispenser] tx [9052aa95a59e3b49838540f47a1464d2fded5d71381fb0c634869d0fde62384a]: invalid: cannot open on another address if it has any balance history
[2023-11-17 00:27:19][INFO] Block (re-parse): 815890 (hashes: L:4f4ec / TX:bac6f / M:f8ab5 [overwrote 2f2b0667fe2f51947d92d745d56f920ca0dedb37049f6993a19175ccecf7c04d])
[2023-11-17 00:27:25][INFO] Block (re-parse): 815900 (hashes: L:37bac / TX:981fd / M:316df [overwrote 466c261e210ffbad672131cea3de3d3412379c3dd84725df6dcffa1ca3fe9a96])
[2023-11-17 00:27:32][INFO] Block (re-parse): 815910 (hashes: L:bd3cd / TX:3d234 / M:ad888 [overwrote 5c5c4035a60c7acca2b8798137b7d301c06ada7f4bc5886fd15594cbdbdce9c6])
[2023-11-17 00:28:46][INFO] Database version number updated.
[2023-11-17 00:28:46][INFO] Reparse took 1437.948 minutes.
[2023-11-17 00:28:46][INFO] Starting database VACUUM. This may take awhile...
[2023-11-17 00:43:14][INFO] Database VACUUM completed.
```

reparse looks good in testing

**Comment by jdogresorg** [comment]
## Bootstrap parse to current
```
[2023-11-17 17:30:47][INFO] Running v1.1.5 of counterparty-server.
[2023-11-17 17:30:47][INFO] Running v9.60.2 of counterparty-lib.
[2023-11-17 17:30:47][INFO] Acquiring lock.
[2023-11-17 17:30:47][INFO] Connecting to database (SQLite 3.24.0-r1).
[2023-11-17 17:30:47][INFO] Connecting to backend.
[2023-11-17 17:30:47][INFO] AddrIndexRs connecting...
[2023-11-17 17:30:47][INFO] Connected to AddrIndexRs!
[2023-11-17 17:30:47][INFO] Starting API Server.
[2023-11-17 17:30:52][INFO] Resuming parsing.
[2023-11-17 17:30:56][INFO] Dispense: 0.6 OXBT from 18KYoyYMVw7ApjjwTyafYRxNxcXoLehJ7Z to bc1qtscmqe5mc5s4jhc8n5cre40xkxwzxf2u4hyfn0 (93feff3e671fb2d9d240b0f50c09dcfa390d59c3fb19fa522d6fc64130182e1e)
[2023-11-17 17:30:56][INFO] Block: 815911 (4.69s, hashes: L:3f76e / TX:4b61b / M:e4e0e)
[2023-11-17 17:31:01][INFO] Block: 815912 (4.77s, hashes: L:410ea / TX:f30f6 / M:8b815)
[2023-11-17 17:31:05][INFO] Dispense: 0.099 OXBT from 13Fgw7pNjyEkZGVMff22qPefKQVayxMwSV to 1HHiuZfYfHt9XFtGYAZsKkw2xjpbECFQ51 (fd323bcacc00dc51f880c3862574973e46c3ed6a95a948655fcb0b78cea9b019)
[2023-11-17 17:31:05][INFO] Dispense: 3 OGPASS from bc1qctuufegsl57sh4dmdsqxsn3trxppd50czedufq to 3HC6qTEyb7WzbFUZfmFvMLUH4ECbaSLooV (ee2e24f8b2f059c839f98c6ab1c4721b268179f347e1f10ba82cb163059672e0)
[2023-11-17 17:31:05][INFO] Dispense: 4.2 OXBT from 18KYoyYMVw7ApjjwTyafYRxNxcXoLehJ7Z to bc1qrfu8sucfzntl8de3z8qglwvzt7acmcan3ank2h (569d568c69a0e39aa3e256977ad9c83d3a1fa7653cdaeb5217766037268aec95)
[2023-11-17 17:31:05][INFO] Block: 815913 (3.81s, hashes: L:a3b16 / TX:e3681 / M:5144b)
[2023-11-17 17:31:08][INFO] Block: 815914 (3.57s, hashes: L:cab4c / TX:3c4c6 / M:4aabe)
...
[2023-11-17 18:32:05][INFO] Order Match: 1 RESURKEKTION for 28.0 XCP (5ca09039851135a8987ce9b929af704220db826887d3c92823cfa811534e4b7a_7f0adfd5fff0cbf610dc2874a51d46e55e7883624944fe35838c1fbb027c3cd0) [completed]
[2023-11-17 18:32:05][INFO] Dispense: 1000 A1919201067688294100 from 1BwL4H8u8apPau6v3PKKy1RcDMjXK8BcTX to bc1qc2y4s4xkyx6zemydkflfre2t6a45k9fahqr5dl (3435e1392f2db6ed0309e562ac5b2ee4bb93fb0ae7f59b2729cd89f69639bdbc)
[2023-11-17 18:32:05][INFO] Block: 817207 (3.47s, hashes: L:a684a / TX:850e7 / M:ed213)
[2023-11-17 18:32:08][INFO] Expired order: 6921ee4e9edc3c7654ef8cb2b13a0dc79ed843bfe3dd262f7329eeb0eb3e2017
[2023-11-17 18:32:08][INFO] Block: 817208 (2.58s, hashes: L:5c53c / TX:ca537 / M:1e769)
[2023-11-17 18:32:17][INFO] Block: 817209 (9.45s, hashes: L:93c0d / TX:3056b / M:10c00)
[2023-11-17 18:32:20][INFO] Mempool cache initialized: 2.59s for 20,000 transactions
[2023-11-17 18:32:20][INFO] Ready for queries.

```

**Comment by jdogresorg** [comment]
## Bootstrap parse to current
```
[2023-11-17 17:30:47][INFO] Running v1.1.5 of counterparty-server.
[2023-11-17 17:30:47][INFO] Running v9.61.0 of counterparty-lib.
[2023-11-17 17:30:47][INFO] Acquiring lock.
[2023-11-17 17:30:47][INFO] Connecting to database (SQLite 3.24.0-r1).
[2023-11-17 17:30:47][INFO] Connecting to backend.
[2023-11-17 17:30:47][INFO] AddrIndexRs connecting...
[2023-11-17 17:30:47][INFO] Connected to AddrIndexRs!
[2023-11-17 17:30:47][INFO] Starting API Server.
[2023-11-17 17:30:52][INFO] Resuming parsing.
[2023-11-17 17:30:56][INFO] Dispense: 0.6 OXBT from 18KYoyYMVw7ApjjwTyafYRxNxcXoLehJ7Z to bc1qtscmqe5mc5s4jhc8n5cre40xkxwzxf2u4hyfn0 (93feff3e671fb2d9d240b0f50c09dcfa390d59c3fb19fa522d6fc64130182e1e)
[2023-11-17 17:30:56][INFO] Block: 815911 (4.69s, hashes: L:3f76e / TX:4b61b / M:e4e0e)
[2023-11-17 17:31:01][INFO] Block: 815912 (4.77s, hashes: L:410ea / TX:f30f6 / M:8b815)
[2023-11-17 17:31:05][INFO] Dispense: 0.099 OXBT from 13Fgw7pNjyEkZGVMff22qPefKQVayxMwSV to 1HHiuZfYfHt9XFtGYAZsKkw2xjpbECFQ51 (fd323bcacc00dc51f880c3862574973e46c3ed6a95a948655fcb0b78cea9b019)
[2023-11-17 17:31:05][INFO] Dispense: 3 OGPASS from bc1qctuufegsl57sh4dmdsqxsn3trxppd50czedufq to 3HC6qTEyb7WzbFUZfmFvMLUH4ECbaSLooV (ee2e24f8b2f059c839f98c6ab1c4721b268179f347e1f10ba82cb163059672e0)
[2023-11-17 17:31:05][INFO] Dispense: 4.2 OXBT from 18KYoyYMVw7ApjjwTyafYRxNxcXoLehJ7Z to bc1qrfu8sucfzntl8de3z8qglwvzt7acmcan3ank2h (569d568c69a0e39aa3e256977ad9c83d3a1fa7653cdaeb5217766037268aec95)
[2023-11-17 17:31:05][INFO] Block: 815913 (3.81s, hashes: L:a3b16 / TX:e3681 / M:5144b)
[2023-11-17 17:31:08][INFO] Block: 815914 (3.57s, hashes: L:cab4c / TX:3c4c6 / M:4aabe)
...
[2023-11-17 18:32:05][INFO] Order Match: 1 RESURKEKTION for 28.0 XCP (5ca09039851135a8987ce9b929af704220db826887d3c92823cfa811534e4b7a_7f0adfd5fff0cbf610dc2874a51d46e55e7883624944fe35838c1fbb027c3cd0) [completed]
[2023-11-17 18:32:05][INFO] Dispense: 1000 A1919201067688294100 from 1BwL4H8u8apPau6v3PKKy1RcDMjXK8BcTX to bc1qc2y4s4xkyx6zemydkflfre2t6a45k9fahqr5dl (3435e1392f2db6ed0309e562ac5b2ee4bb93fb0ae7f59b2729cd89f69639bdbc)
[2023-11-17 18:32:05][INFO] Block: 817207 (3.47s, hashes: L:a684a / TX:850e7 / M:ed213)
[2023-11-17 18:32:08][INFO] Expired order: 6921ee4e9edc3c7654ef8cb2b13a0dc79ed843bfe3dd262f7329eeb0eb3e2017
[2023-11-17 18:32:08][INFO] Block: 817208 (2.58s, hashes: L:5c53c / TX:ca537 / M:1e769)
[2023-11-17 18:32:17][INFO] Block: 817209 (9.45s, hashes: L:93c0d / TX:3056b / M:10c00)
[2023-11-17 18:32:20][INFO] Mempool cache initialized: 2.59s for 20,000 transactions
[2023-11-17 18:32:20][INFO] Ready for queries.
```

## Parse 100 blocks after rollback
```
[2023-11-17 18:54:40][INFO] Running v1.1.5 of counterparty-server.
[2023-11-17 18:54:40][INFO] Running v9.61.0 of counterparty-lib.
[2023-11-17 18:54:40][INFO] Acquiring lock.
[2023-11-17 18:54:40][INFO] Connecting to database (SQLite 3.24.0-r1).
[2023-11-17 18:54:40][INFO] Connecting to backend.
[2023-11-17 18:54:40][INFO] AddrIndexRs connecting...
[2023-11-17 18:54:40][INFO] Connected to AddrIndexRs!
[2023-11-17 18:54:40][INFO] Starting API Server.
[2023-11-17 18:54:44][INFO] Resuming parsing.
[2023-11-17 18:54:46][INFO] Expired order: 0358a267e6ef8f1a42db84849cb3c729de848269d26007879dd7378b9cef0e15
[2023-11-17 18:54:46][INFO] Block: 817110 (2.50s, hashes: L:dea04 / TX:5c024 / M:c2270)
[2023-11-17 18:54:48][INFO] Dispense: 8 OGPASS from bc1qctuufegsl57sh4dmdsqxsn3trxppd50czedufq to 33uL398AYw8Dt3qAgK4m4JuPnvtbKUqVBg (bee3eeab7bcf5cc399983eeb18b5f4a208d8f0d286cd4d1633bb0b3e1f30abd1)
[2023-11-17 18:54:48][INFO] Block: 817111 (2.07s, hashes: L:378d9 / TX:12d46 / M:529bd)
[2023-11-17 18:54:51][INFO] Dispense: 20 OGPASS from bc1qctuufegsl57sh4dmdsqxsn3trxppd50czedufq to 3Qw2JmuinUC1TPm4vnzPcAbxxWSPt97vjz (dbbfe410ccbe454e8ef8e482f4273233a7466fcc95f9a82e5205e195ef4a37c4)
[2023-11-17 18:54:51][INFO] Block: 817112 (2.80s, hashes: L:806cc / TX:aa2c1 / M:e0ca6)
[2023-11-17 18:54:54][INFO] Block: 817113 (3.28s, hashes: L:405e0 / TX:365e4 / M:e8a3d)
...
[2023-11-17 18:59:39][INFO] Block: 817209 (2.26s, hashes: L:93c0d / TX:3056b / M:10c00)
[2023-11-17 18:59:43][INFO] Dispense: 0.0983 OXBT from 13Fgw7pNjyEkZGVMff22qPefKQVayxMwSV to 16dvYJ6CxgMcoVDKALDjjULKNnfdKi83h3 (25a028f8c0c3f3b1a679ad1d987f9f36e4350385f0aa2959b4d95255d2b8e23c)
[2023-11-17 18:59:43][INFO] Block: 817210 (3.96s, hashes: L:be521 / TX:9f2f6 / M:cbf70)
[2023-11-17 18:59:46][INFO] Block: 817211 (2.88s, hashes: L:042c6 / TX:bd3ef / M:45f7c)
[2023-11-17 18:59:56][INFO] Block: 817212 (9.50s, hashes: L:5c8c6 / TX:2f78f / M:86a03)
[2023-11-17 18:59:58][INFO] Mempool cache initialized: 2.26s for 20,000 transactions
[2023-11-17 18:59:58][INFO] Ready for queries.
```

Looks good in testing

**Comment by jotapea** [comment]
CIP-Discussion: https://github.com/CounterpartyXCP/cips/discussions/124

**Comment by Jpja** [comment]
I appreciate all the work put into this but strongly recommend we put the release on hold. Some changes lack justification.

* Adjusted DEFAULT_MULTISIG_DUST_SIZE (7800->1000)
* Fixed issue with Asset description deleted when null 
* Added support for triggering dispenses on all tx outputs
* Added DISPENSER_CLOSE_DELAY to delay closing dispensers 5 blocks

Click on link in OP to view my concerns.

Once concerns from the community are ironed out, we can continue the release.

_Not in the notes but I heard new IDs will be assigned to issuances. I'd prefer to, once new IDs are introduced, to add a additional improvements at the same time. Like using one bit, not byte, per flag. Have additional free flags for future improvements (like locking descriptions. Make the subasset ID equal its hash to reduce API reliance for light wallets. All of these changes will free up space for the asset description, and make immutable hashes easier to fit inside op_return._

**Comment by jotapea** [comment]
In this case, "put the release on hold" means:

- Deleting v9.61.0 from https://github.com/CounterpartyXCP/counterparty-lib/releases
- Making the `master` branch up to commit https://github.com/CounterpartyXCP/counterparty-lib/commit/09b20b3e1848481bed2fec3dba10c4cc11e5095e
- Optionally, keep current master's commit history in a new branch

**Comment by jotapea** [comment]
> Not in the notes but I heard new IDs will be assigned to issuances. I'd prefer to, once new IDs are introduced, to add a additional improvements at the same time. Like using one bit, not byte, per flag. Have additional free flags for future improvements (like locking descriptions. Make the subasset ID equal its hash to reduce API reliance for light wallets. All of these changes will free up space for the asset description, and make immutable hashes easier to fit inside op_return.

This is gold @Jpja, from the first sentence to the last.

**Comment by jotapea** [comment]
> rm -rf data/addrindexrs/*
> rm -rf data/counterparty/*

This part of the instructions is deleting symlinks. What is the purpose of doing this? Because these symlinks are not deleting the source file, or are they?

And if they are, then these instructions are for a full parse, right? (Not considering the bootstrap.)

**Comment by jotapea** [comment]
(Was too busy TRYING to prevent the update in the first place, as I had unresolved concerns. And the process itself is broken if this is supposed to be a decentralized network... I would just have done things VERY different from you in terms of being considerate with other node operators... but I'm past that at this point.)

xcp.dev is still in v9.60.1 (and will be for a while, as I have no other option until my new version node is ready).

I'm talking about what I am seeing directly from the fednode logs, a v9.60.1 node I'm upgrading to to v9.61.0. Why do you think I could be seeing different hashes (all of them, not only messages) from such early ~300000 blocks in the reparse?

**Comment by jotapea** [comment]
About the symlinks / directory, I have nothing under `data`, is empty. It is an open issue https://github.com/CounterpartyXCP/federatednode/issues/343.

**Comment by jdogresorg** [comment]
> Why do you think I could be seeing different hashes (all of them, not only messages) from such early ~300000 blocks in the reparse?

I can't speak to that, other than to say that if you follow the upgrade instructions and make sure your on the latest counterparty-lib, addrindexrs, and rebuild your addrindexrs data, your parsing and hashes should match.

I just started a full parse here and I am not seeing any mismatches when comparing with your xcp.dev site... the hashes match

FYI, the counterparty-lib log shows the last 5 characters from the END of the hash... maybe that is why your seeing mismatches? trying to compare first 5 characters of hash instead of last 5? 

Either way... in my quick full parse spot check, I am not seeing the same behavior as you, as all of the hashes match exactly as they should.

```
[2023-12-01 14:53:02][INFO] Running v1.1.5 of counterparty-server.
[2023-12-01 14:53:02][INFO] Running v9.61.0 of counterparty-lib.
[2023-12-01 14:53:02][INFO] Acquiring lock.
[2023-12-01 14:53:02][INFO] Connecting to database (SQLite 3.24.0-r1).
[2023-12-01 14:53:02][INFO] Connecting to backend.
[2023-12-01 14:53:02][INFO] AddrIndexRs connecting...
[2023-12-01 14:53:02][INFO] Connected to AddrIndexRs!
[2023-12-01 15:01:22][INFO] Starting API Server.
[2023-12-01 15:01:22][WARNING] New database.
[2023-12-01 15:01:22][INFO] Resuming parsing.
[2023-12-01 15:01:22][INFO] Block: 278270 (0.12s, hashes: L:7b0b7 / TX:7b0b7 / M:7b0b7)
[2023-12-01 15:01:23][INFO] Block: 278271 (0.15s, hashes: L:f705f / TX:f705f / M:f705f)
[2023-12-01 15:01:23][INFO] Block: 278272 (0.08s, hashes: L:03a20 / TX:03a20 / M:03a20)
[2023-12-01 15:01:23][INFO] Block: 278273 (0.16s, hashes: L:6f1bd / TX:6f1bd / M:6f1bd)
[2023-12-01 15:01:23][INFO] Block: 278274 (0.27s, hashes: L:cd646 / TX:cd646 / M:cd646)
[2023-12-01 15:01:23][INFO] Block: 278275 (0.07s, hashes: L:c4319 / TX:c4319 / M:c4319)
[2023-12-01 15:01:23][INFO] Block: 278276 (0.12s, hashes: L:72171 / TX:72171 / M:72171)
[2023-12-01 15:01:23][INFO] Block: 278277 (0.07s, hashes: L:b4e12 / TX:b4e12 / M:b4e12)
[2023-12-01 15:01:23][INFO] Block: 278278 (0.09s, hashes: L:e2ab8 / TX:e2ab8 / M:e2ab8)
[2023-12-01 15:01:23][INFO] Block: 278279 (0.08s, hashes: L:dc9a7 / TX:dc9a7 / M:dc9a7)
[2023-12-01 15:01:24][INFO] Block: 278280 (0.15s, hashes: L:95a76 / TX:95a76 / M:95a76)
[2023-12-01 15:01:24][INFO] Block: 278281 (0.25s, hashes: L:5a541 / TX:5a541 / M:5a541)
[2023-12-01 15:01:24][INFO] Block: 278282 (0.12s, hashes: L:11e5e / TX:11e5e / M:11e5e)
[2023-12-01 15:01:24][INFO] Block: 278283 (0.18s, hashes: L:63559 / TX:63559 / M:63559)
```

image

image

image

**Comment by jdogresorg** [comment]
also... you can force a full parse via the following method
```
cd federatednode/
fednode stop counterparty counterparty-testnet
sudo su
rm -rf data/counterparty/*
rm -rf data/addrindexrs/*
touch data/counterparty/counterparty.db
touch data/counterparty/counterparty.testnet.db
exit
fednode start counterparty counterparty-testnet
```

when CP starts up, if it detects NO database, it downloads the bootstrap.... if however, you delete the database, then create an EMPTY database via touch, when CP starts up, it will resume parsing where the database let off... since the database is empty, counterparty-lib will start parsing data at the first block.

deleting / touching counterparty.db is prolly a faster way to do a full parse than having to do a full uninstall/install just to use the `--no-bootstrap` option

Hope this helps on your full parse... I'll let the full parse finish here as well and verify all is good still :)

**Comment by jotapea** [comment]
@jdogresorg has your full parse finished? The default www.xcp.dev is now in v9.61, but my hashes are not matching yours at xchain...

**Pull request merged**
